-- =========================================================
-- 0. OPTIONAL DROP (필요할 때만 수동 실행)
-- 순서 주의: FK -> TABLE -> SEQUENCE
-- =========================================================
-- ALTER TABLE ANSWER DROP CONSTRAINT FK_ANSWER_SUGGESTION;
-- ALTER TABLE ANSWER DROP CONSTRAINT FK_ANSWER_WRITER_EMP;
-- ALTER TABLE NOTICE_BOARD DROP CONSTRAINT FK_NOTICE_BOARD_WRITER_EMP;
-- ALTER TABLE EQUIPMENT_FAILURE_ACTION DROP CONSTRAINT FK_EFA_MAINTENANCE;
-- ALTER TABLE SUGGESTION_BOARD DROP CONSTRAINT FK_SUGGESTION_BOARD_WRITER_EMP;
-- ALTER TABLE ROUTING DROP CONSTRAINT FK_ROUTING_ITEM;
-- ALTER TABLE ROUTING DROP CONSTRAINT FK_ROUTING_PROCESS;
-- ALTER TABLE ROUTING DROP CONSTRAINT FK_ROUTING_EQUIPMENT;
-- ALTER TABLE INVENTORY DROP CONSTRAINT FK_INVENTORY_ITEM;
-- ALTER TABLE MATERIAL_INOUT DROP CONSTRAINT FK_MATERIAL_INOUT_ITEM;
-- ALTER TABLE WORK_ORDER DROP CONSTRAINT FK_WORK_ORDER_ITEM;
-- ALTER TABLE WORK_ORDER DROP CONSTRAINT FK_WORK_ORDER_PLAN;
-- ALTER TABLE WORK_ORDER DROP CONSTRAINT FK_WORK_ORDER_EMP;
-- ALTER TABLE EQUIPMENT_MAINTENANCE DROP CONSTRAINT FK_EQUIPMENT_MAINTENANCE_EQUIPMENT;
-- ALTER TABLE FINAL_INSPECTION DROP CONSTRAINT FK_FINAL_INSPECTION_RESULT;
-- ALTER TABLE FINAL_INSPECTION DROP CONSTRAINT FK_FINAL_INSPECTION_EMP;
-- ALTER TABLE BOM DROP CONSTRAINT FK_BOM_ITEM;
-- ALTER TABLE BOM_DETAIL DROP CONSTRAINT FK_BOM_DETAIL_BOM;
-- ALTER TABLE BOM_DETAIL DROP CONSTRAINT FK_BOM_DETAIL_ITEM;
-- ALTER TABLE PRODUCTION_PLAN DROP CONSTRAINT FK_PRODUCTION_PLAN_ITEM;
-- ALTER TABLE DEFECT_PRODUCT DROP CONSTRAINT FK_DEFECT_PRODUCT_FINAL_INSPECTION;
-- ALTER TABLE DEFECT_PRODUCT DROP CONSTRAINT FK_DEFECT_PRODUCT_CODE;
-- ALTER TABLE PRODUCTION_RESULT DROP CONSTRAINT FK_PRODUCTION_RESULT_WORK_ORDER;
-- ALTER TABLE DEFECT_MATERIAL DROP CONSTRAINT FK_DEFECT_MATERIAL_INSPECTION;
-- ALTER TABLE DEFECT_MATERIAL DROP CONSTRAINT FK_DEFECT_MATERIAL_CODE;
-- ALTER TABLE MATERIAL_INSPECTION DROP CONSTRAINT FK_MATERIAL_INSPECTION_ITEM;
-- ALTER TABLE MATERIAL_INSPECTION DROP CONSTRAINT FK_MATERIAL_INSPECTION_EMP;
--
-- DROP TABLE ANSWER CASCADE CONSTRAINTS;
-- DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
-- DROP TABLE EQUIPMENT_FAILURE_ACTION CASCADE CONSTRAINTS;
-- DROP TABLE SUGGESTION_BOARD CASCADE CONSTRAINTS;
-- DROP TABLE ROUTING CASCADE CONSTRAINTS;
-- DROP TABLE INVENTORY CASCADE CONSTRAINTS;
-- DROP TABLE MATERIAL_INOUT CASCADE CONSTRAINTS;
-- DROP TABLE WORK_ORDER CASCADE CONSTRAINTS;
-- DROP TABLE EQUIPMENT_MAINTENANCE CASCADE CONSTRAINTS;
-- DROP TABLE FINAL_INSPECTION CASCADE CONSTRAINTS;
-- DROP TABLE BOM_DETAIL CASCADE CONSTRAINTS;
-- DROP TABLE BOM CASCADE CONSTRAINTS;
-- DROP TABLE PRODUCTION_PLAN CASCADE CONSTRAINTS;
-- DROP TABLE DEFECT_PRODUCT CASCADE CONSTRAINTS;
-- DROP TABLE PRODUCTION_RESULT CASCADE CONSTRAINTS;
-- DROP TABLE DEFECT_MATERIAL CASCADE CONSTRAINTS;
-- DROP TABLE MATERIAL_INSPECTION CASCADE CONSTRAINTS;
-- DROP TABLE PROCESS CASCADE CONSTRAINTS;
-- DROP TABLE ITEM CASCADE CONSTRAINTS;
-- DROP TABLE DEFECT_CODE CASCADE CONSTRAINTS;
-- DROP TABLE EMP CASCADE CONSTRAINTS;
-- DROP TABLE EQUIPMENT CASCADE CONSTRAINTS;
--
-- DROP SEQUENCE SEQ_PROCESS;
-- DROP SEQUENCE SEQ_ANSWER;
-- DROP SEQUENCE SEQ_NOTICE_BOARD;
-- DROP SEQUENCE SEQ_EQUIPMENT_FAILURE_ACTION;
-- DROP SEQUENCE SEQ_ITEM;
-- DROP SEQUENCE SEQ_SUGGESTION_BOARD;
-- DROP SEQUENCE SEQ_ROUTING;
-- DROP SEQUENCE SEQ_INVENTORY;
-- DROP SEQUENCE SEQ_MATERIAL_INOUT;
-- DROP SEQUENCE SEQ_WORK_ORDER;
-- DROP SEQUENCE SEQ_DEFECT_CODE;
-- DROP SEQUENCE SEQ_EQUIPMENT_MAINTENANCE;
-- DROP SEQUENCE SEQ_FINAL_INSPECTION;
-- DROP SEQUENCE SEQ_EMP;
-- DROP SEQUENCE SEQ_BOM;
-- DROP SEQUENCE SEQ_BOM_DETAIL;
-- DROP SEQUENCE SEQ_PRODUCTION_PLAN;
-- DROP SEQUENCE SEQ_DEFECT_PRODUCT;
-- DROP SEQUENCE SEQ_PRODUCTION_RESULT;
-- DROP SEQUENCE SEQ_EQUIPMENT;
-- DROP SEQUENCE SEQ_DEFECT_MATERIAL;
-- DROP SEQUENCE SEQ_MATERIAL_INSPECTION;


-- =========================================================
-- 1. TABLE CREATE
-- =========================================================

CREATE TABLE PROCESS (
    PROCESS_ID          NUMBER          NOT NULL,
    PROCESS_CODE        VARCHAR2(30)    NULL,
    PROCESS_NAME        VARCHAR2(100)   NULL,
    REQUIRED_WORKERS    NUMBER          NULL,
    DESCRIPTION         VARCHAR2(500)   NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE ANSWER (
    ANSWER_ID           NUMBER          NOT NULL,
    SUGGESTION_ID       NUMBER          NOT NULL,
    CONTENT             CLOB            NULL,
    WRITER_EMP_ID       NUMBER          NOT NULL,
    STATUS              VARCHAR2(20)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE NOTICE_BOARD (
    NOTICE_ID           NUMBER          NOT NULL,
    TITLE               VARCHAR2(200)   NULL,
    CONTENT             CLOB            NULL,
    WRITER_EMP_ID       NUMBER          NOT NULL,
    STATUS              VARCHAR2(20)    NULL,
    VIEW_COUNT          NUMBER          NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE EQUIPMENT_FAILURE_ACTION (
    EQUIPMENT_FAILURE_ACTION_ID NUMBER       NOT NULL,
    MAINTENANCE_ID             NUMBER        NOT NULL,
    FAILURE_DATE               DATE          NULL,
    FAILURE_PART               VARCHAR2(100) NULL,
    FAILURE_CONTENT            VARCHAR2(500) NULL,
    CAUSE_TEXT                 VARCHAR2(500) NULL,
    ACTION_TEXT                VARCHAR2(500) NULL,
    ACTION_DATE                DATE          NULL,
    STATUS                     VARCHAR2(20)  NULL,
    REMARK                     VARCHAR2(300) NULL,
    CREATED_AT                 DATE          NULL,
    UPDATED_AT                 DATE          NULL
);

CREATE TABLE ITEM (
    ITEM_ID             NUMBER          NOT NULL,
    ITEM_CODE           VARCHAR2(30)    NULL,
    ITEM_NAME           VARCHAR2(100)   NULL,
    ITEM_TYPE           VARCHAR2(20)    NULL,
    UNIT                VARCHAR2(20)    NULL,
    SPEC                VARCHAR2(100)   NULL,
    SUPPLIER_NAME       VARCHAR2(100)   NULL,
    SAFETY_STOCK        NUMBER(15,3)    NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE SUGGESTION_BOARD (
    SUGGESTION_ID       NUMBER          NOT NULL,
    TITLE               VARCHAR2(200)   NULL,
    CONTENT             CLOB            NULL,
    WRITER_EMP_ID       NUMBER          NOT NULL,
    STATUS              VARCHAR2(20)    NULL,
    VIEW_COUNT          NUMBER          NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE ROUTING (
    ROUTING_ID          NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    PROCESS_ID          NUMBER          NOT NULL,
    PROCESS_SEQ         NUMBER          NULL,
    EQUIPMENT_ID        NUMBER          NOT NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE INVENTORY (
    INVENTORY_ID        NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    QTY_ON_HAND         NUMBER(15,3)    NULL,
    SAFETY_STOCK        NUMBER(15,3)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE MATERIAL_INOUT (
    INOUT_ID            NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    INOUT_TYPE          VARCHAR2(10)    NULL,
    QTY                 NUMBER(15,3)    NULL,
    UNIT                VARCHAR2(20)    NULL,
    INOUT_DATE          DATE            NULL,
    STATUS              VARCHAR2(20)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE WORK_ORDER (
    WORK_ORDER_ID       NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    PLAN_ID             NUMBER          NOT NULL,
    EMP_ID              NUMBER          NOT NULL,
    WORK_DATE           DATE            NULL,
    WORK_QTY            NUMBER(15,3)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE DEFECT_CODE (
    DEFECT_CODE_ID      NUMBER          NOT NULL,
    DEFECT_CODE         VARCHAR2(30)    NOT NULL,
    DEFECT_NAME         VARCHAR2(100)   NULL,
    DEFECT_TYPE         VARCHAR2(20)    NULL,
    DESCRIPTION         VARCHAR2(500)   NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE EQUIPMENT_MAINTENANCE (
    MAINTENANCE_ID          NUMBER          NOT NULL,
    EQUIPMENT_ID            NUMBER          NOT NULL,
    MAINTENANCE_DATE        DATE            NULL,
    MAINTENANCE_TYPE        VARCHAR2(20)    NULL,
    MAINTENANCE_CONTENT     VARCHAR2(500)   NULL,
    NEXT_MAINTENANCE_DATE   DATE            NULL,
    REMARK                  VARCHAR2(300)   NULL,
    CREATED_AT              DATE            NULL,
    UPDATED_AT              DATE            NULL
);

CREATE TABLE FINAL_INSPECTION (
    FINAL_INSPECTION_ID NUMBER          NOT NULL,
    RESULT_ID           NUMBER          NOT NULL,
    EMP_ID              NUMBER          NOT NULL,
    INSPECT_QTY         NUMBER(15,3)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    INSPECTION_DATE     DATE            NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE EMP (
    EMP_ID              NUMBER          NOT NULL,
    EMP_NO              VARCHAR2(20)    NULL,
    EMP_NAME            VARCHAR2(50)    NULL,
    PASSWORD_HASH       VARCHAR2(256)   NULL,
    DEPT_CODE           VARCHAR2(20)    NULL,
    POSITION_NAME       VARCHAR2(30)    NULL,
    EMAIL               VARCHAR2(100)   NULL,
    PHONE               VARCHAR2(20)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    ROLE_NAME           VARCHAR2(20)    NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE BOM (
    BOM_ID              NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    VERSION_NO          NUMBER          NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE BOM_DETAIL (
    BOM_DETAIL_ID       NUMBER          NOT NULL,
    BOM_ID              NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    QTY_REQUIRED        NUMBER(15,3)    NULL,
    UNIT                VARCHAR2(20)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE PRODUCTION_PLAN (
    PLAN_ID             NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    PLAN_DATE           DATE            NULL,
    PLAN_QTY            NUMBER(15,3)    NULL,
    LINE_CODE           VARCHAR2(30)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE DEFECT_PRODUCT (
    DEFECT_PRODUCT_ID   NUMBER          NOT NULL,
    FINAL_INSPECTION_ID NUMBER          NOT NULL,
    DEFECT_CODE_ID      NUMBER          NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE PRODUCTION_RESULT (
    RESULT_ID           NUMBER          NOT NULL,
    WORK_ORDER_ID       NUMBER          NOT NULL,
    RESULT_DATE         DATE            NULL,
    LOT_NO              VARCHAR2(50)    NULL,
    PRODUCED_QTY        NUMBER(15,3)    NULL,
    LOSS_QTY            NUMBER(15,3)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID        NUMBER          NOT NULL,
    EQUIPMENT_CODE      VARCHAR2(30)    NULL,
    EQUIPMENT_NAME      VARCHAR2(100)   NULL,
    MODEL_NAME          VARCHAR2(100)   NULL,
    LOCATION            VARCHAR2(100)   NULL,
    MANUFACTURER        VARCHAR2(100)   NULL,
    VENDOR_NAME         VARCHAR2(100)   NULL,
    EQUIPMENT_PRICE     NUMBER          NULL,
    PURCHASE_DATE       DATE            NULL,
    USE_YN              CHAR(1)         NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL
);

CREATE TABLE DEFECT_MATERIAL (
    DEFECT_MATERIAL_ID      NUMBER          NOT NULL,
    MATERIAL_INSPECTION_ID  NUMBER          NOT NULL,
    DEFECT_CODE_ID          NUMBER          NOT NULL,
    REMARK                  VARCHAR2(300)   NULL,
    CREATED_AT              DATE            NULL,
    UPDATED_AT              DATE            NULL
);

CREATE TABLE MATERIAL_INSPECTION (
    MATERIAL_INSPECTION_ID  NUMBER          NOT NULL,
    ITEM_ID                 NUMBER          NOT NULL,
    EMP_ID                  NUMBER          NOT NULL,
    INSPECT_QTY             NUMBER(15,3)    NULL,
    GOOD_QTY                NUMBER(15,3)    NULL,
    DEFECT_QTY              NUMBER(15,3)    NULL,
    RESULT                  VARCHAR2(20)    NULL,
    INSPECTION_DATE         DATE            NULL,
    REMARK                  VARCHAR2(300)   NULL,
    CREATED_AT              DATE            NULL,
    UPDATED_AT              DATE            NULL
);


-- =========================================================
-- 2. PRIMARY KEY
-- =========================================================

ALTER TABLE PROCESS ADD CONSTRAINT PK_PROCESS PRIMARY KEY (PROCESS_ID);
ALTER TABLE ANSWER ADD CONSTRAINT PK_ANSWER PRIMARY KEY (ANSWER_ID);
ALTER TABLE NOTICE_BOARD ADD CONSTRAINT PK_NOTICE_BOARD PRIMARY KEY (NOTICE_ID);
ALTER TABLE EQUIPMENT_FAILURE_ACTION ADD CONSTRAINT PK_EQUIPMENT_FAILURE_ACTION PRIMARY KEY (EQUIPMENT_FAILURE_ACTION_ID);
ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID);
ALTER TABLE SUGGESTION_BOARD ADD CONSTRAINT PK_SUGGESTION_BOARD PRIMARY KEY (SUGGESTION_ID);
ALTER TABLE ROUTING ADD CONSTRAINT PK_ROUTING PRIMARY KEY (ROUTING_ID);
ALTER TABLE INVENTORY ADD CONSTRAINT PK_INVENTORY PRIMARY KEY (INVENTORY_ID);
ALTER TABLE MATERIAL_INOUT ADD CONSTRAINT PK_MATERIAL_INOUT PRIMARY KEY (INOUT_ID);
ALTER TABLE WORK_ORDER ADD CONSTRAINT PK_WORK_ORDER PRIMARY KEY (WORK_ORDER_ID);
ALTER TABLE DEFECT_CODE ADD CONSTRAINT PK_DEFECT_CODE PRIMARY KEY (DEFECT_CODE_ID);
ALTER TABLE EQUIPMENT_MAINTENANCE ADD CONSTRAINT PK_EQUIPMENT_MAINTENANCE PRIMARY KEY (MAINTENANCE_ID);
ALTER TABLE FINAL_INSPECTION ADD CONSTRAINT PK_FINAL_INSPECTION PRIMARY KEY (FINAL_INSPECTION_ID);
ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (EMP_ID);
ALTER TABLE BOM ADD CONSTRAINT PK_BOM PRIMARY KEY (BOM_ID);
ALTER TABLE BOM_DETAIL ADD CONSTRAINT PK_BOM_DETAIL PRIMARY KEY (BOM_DETAIL_ID);
ALTER TABLE PRODUCTION_PLAN ADD CONSTRAINT PK_PRODUCTION_PLAN PRIMARY KEY (PLAN_ID);
ALTER TABLE DEFECT_PRODUCT ADD CONSTRAINT PK_DEFECT_PRODUCT PRIMARY KEY (DEFECT_PRODUCT_ID);
ALTER TABLE PRODUCTION_RESULT ADD CONSTRAINT PK_PRODUCTION_RESULT PRIMARY KEY (RESULT_ID);
ALTER TABLE EQUIPMENT ADD CONSTRAINT PK_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID);
ALTER TABLE DEFECT_MATERIAL ADD CONSTRAINT PK_DEFECT_MATERIAL PRIMARY KEY (DEFECT_MATERIAL_ID);
ALTER TABLE MATERIAL_INSPECTION ADD CONSTRAINT PK_MATERIAL_INSPECTION PRIMARY KEY (MATERIAL_INSPECTION_ID);


-- =========================================================
-- 3. FOREIGN KEY
-- =========================================================

ALTER TABLE ANSWER
    ADD CONSTRAINT FK_ANSWER_SUGGESTION
    FOREIGN KEY (SUGGESTION_ID)
    REFERENCES SUGGESTION_BOARD (SUGGESTION_ID);

ALTER TABLE ANSWER
    ADD CONSTRAINT FK_ANSWER_WRITER_EMP
    FOREIGN KEY (WRITER_EMP_ID)
    REFERENCES EMP (EMP_ID);

ALTER TABLE NOTICE_BOARD
    ADD CONSTRAINT FK_NOTICE_BOARD_WRITER_EMP
    FOREIGN KEY (WRITER_EMP_ID)
    REFERENCES EMP (EMP_ID);

ALTER TABLE EQUIPMENT_FAILURE_ACTION
    ADD CONSTRAINT FK_EFA_MAINTENANCE
    FOREIGN KEY (MAINTENANCE_ID)
    REFERENCES EQUIPMENT_MAINTENANCE (MAINTENANCE_ID);

ALTER TABLE SUGGESTION_BOARD
    ADD CONSTRAINT FK_SUGGESTION_BOARD_WRITER_EMP
    FOREIGN KEY (WRITER_EMP_ID)
    REFERENCES EMP (EMP_ID);

ALTER TABLE ROUTING
    ADD CONSTRAINT FK_ROUTING_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE ROUTING
    ADD CONSTRAINT FK_ROUTING_PROCESS
    FOREIGN KEY (PROCESS_ID)
    REFERENCES PROCESS (PROCESS_ID);

ALTER TABLE ROUTING
    ADD CONSTRAINT FK_ROUTING_EQUIPMENT
    FOREIGN KEY (EQUIPMENT_ID)
    REFERENCES EQUIPMENT (EQUIPMENT_ID);

ALTER TABLE INVENTORY
    ADD CONSTRAINT FK_INVENTORY_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE MATERIAL_INOUT
    ADD CONSTRAINT FK_MATERIAL_INOUT_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE WORK_ORDER
    ADD CONSTRAINT FK_WORK_ORDER_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE WORK_ORDER
    ADD CONSTRAINT FK_WORK_ORDER_PLAN
    FOREIGN KEY (PLAN_ID)
    REFERENCES PRODUCTION_PLAN (PLAN_ID);

ALTER TABLE WORK_ORDER
    ADD CONSTRAINT FK_WORK_ORDER_EMP
    FOREIGN KEY (EMP_ID)
    REFERENCES EMP (EMP_ID);

ALTER TABLE EQUIPMENT_MAINTENANCE
    ADD CONSTRAINT FK_EQ_MT_EQP
    FOREIGN KEY (EQUIPMENT_ID)
    REFERENCES EQUIPMENT (EQUIPMENT_ID);

ALTER TABLE FINAL_INSPECTION
    ADD CONSTRAINT FK_FINAL_INSPECTION_RESULT
    FOREIGN KEY (RESULT_ID)
    REFERENCES PRODUCTION_RESULT (RESULT_ID);

ALTER TABLE FINAL_INSPECTION
    ADD CONSTRAINT FK_FINAL_INSPECTION_EMP
    FOREIGN KEY (EMP_ID)
    REFERENCES EMP (EMP_ID);

ALTER TABLE BOM
    ADD CONSTRAINT FK_BOM_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE BOM_DETAIL
    ADD CONSTRAINT FK_BOM_DETAIL_BOM
    FOREIGN KEY (BOM_ID)
    REFERENCES BOM (BOM_ID);

ALTER TABLE BOM_DETAIL
    ADD CONSTRAINT FK_BOM_DETAIL_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE PRODUCTION_PLAN
    ADD CONSTRAINT FK_PRODUCTION_PLAN_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE DEFECT_PRODUCT
    ADD CONSTRAINT FK_DF_PRD_FIN
    FOREIGN KEY (FINAL_INSPECTION_ID)
    REFERENCES FINAL_INSPECTION (FINAL_INSPECTION_ID);

ALTER TABLE DEFECT_PRODUCT
    ADD CONSTRAINT FK_DEFECT_PRODUCT_CODE
    FOREIGN KEY (DEFECT_CODE_ID)
    REFERENCES DEFECT_CODE (DEFECT_CODE_ID);

ALTER TABLE PRODUCTION_RESULT
    ADD CONSTRAINT FK_PR_RES_WO
    FOREIGN KEY (WORK_ORDER_ID)
    REFERENCES WORK_ORDER (WORK_ORDER_ID);

ALTER TABLE DEFECT_MATERIAL
    ADD CONSTRAINT FK_DEFECT_MATERIAL_INSPECTION
    FOREIGN KEY (MATERIAL_INSPECTION_ID)
    REFERENCES MATERIAL_INSPECTION (MATERIAL_INSPECTION_ID);

ALTER TABLE DEFECT_MATERIAL
    ADD CONSTRAINT FK_DEFECT_MATERIAL_CODE
    FOREIGN KEY (DEFECT_CODE_ID)
    REFERENCES DEFECT_CODE (DEFECT_CODE_ID);

ALTER TABLE MATERIAL_INSPECTION
    ADD CONSTRAINT FK_MATERIAL_INSPECTION_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

ALTER TABLE MATERIAL_INSPECTION
    ADD CONSTRAINT FK_MATERIAL_INSPECTION_EMP
    FOREIGN KEY (EMP_ID)
    REFERENCES EMP (EMP_ID);


-- =========================================================
-- 4. SEQUENCE
-- 트리거 없음. Java / SQL에서 직접 NEXTVAL 사용
-- =========================================================

CREATE SEQUENCE SEQ_PROCESS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANSWER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_BOARD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EQUIPMENT_FAILURE_ACTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUGGESTION_BOARD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROUTING START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVENTORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MATERIAL_INOUT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WORK_ORDER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEFECT_CODE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EQUIPMENT_MAINTENANCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FINAL_INSPECTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOM_DETAIL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCTION_PLAN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEFECT_PRODUCT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCTION_RESULT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EQUIPMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEFECT_MATERIAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MATERIAL_INSPECTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- =========================================================

COMMIT;
