-- =========================================================
-- CHECK SELECT FOR ALL 22 TABLES
-- =========================================================

SELECT * FROM EMP;
SELECT * FROM PROCESS;
SELECT * FROM ITEM;
SELECT * FROM EQUIPMENT;
SELECT * FROM DEFECT_CODE;

SELECT * FROM SUGGESTION_BOARD;
SELECT * FROM NOTICE_BOARD;
SELECT * FROM ANSWER;

SELECT * FROM INVENTORY;
SELECT * FROM MATERIAL_INOUT;

SELECT * FROM PRODUCTION_PLAN;
SELECT * FROM WORK_ORDER;
SELECT * FROM PRODUCTION_RESULT;
SELECT * FROM FINAL_INSPECTION;

SELECT * FROM MATERIAL_INSPECTION;
SELECT * FROM DEFECT_MATERIAL;
SELECT * FROM DEFECT_PRODUCT;

SELECT * FROM BOM;
SELECT * FROM BOM_DETAIL;
SELECT * FROM ROUTING;

SELECT * FROM EQUIPMENT_MAINTENANCE;
SELECT * FROM EQUIPMENT_FAILURE_ACTION;