-- =========================================
-- SEQUENCE RESET SCRIPT (ALL 22 TABLES)
-- =========================================

-- EMP
DROP SEQUENCE SEQ_EMP;
CREATE SEQUENCE SEQ_EMP START WITH 1 INCREMENT BY 1;

-- PROCESS
DROP SEQUENCE SEQ_PROCESS;
CREATE SEQUENCE SEQ_PROCESS START WITH 1 INCREMENT BY 1;

-- ITEM
DROP SEQUENCE SEQ_ITEM;
CREATE SEQUENCE SEQ_ITEM START WITH 1 INCREMENT BY 1;

-- EQUIPMENT
DROP SEQUENCE SEQ_EQUIPMENT;
CREATE SEQUENCE SEQ_EQUIPMENT START WITH 1 INCREMENT BY 1;

-- DEFECT_CODE
DROP SEQUENCE SEQ_DEFECT_CODE;
CREATE SEQUENCE SEQ_DEFECT_CODE START WITH 1 INCREMENT BY 1;

-- SUGGESTION_BOARD
DROP SEQUENCE SEQ_SUGGESTION_BOARD;
CREATE SEQUENCE SEQ_SUGGESTION_BOARD START WITH 1 INCREMENT BY 1;

-- NOTICE_BOARD
DROP SEQUENCE SEQ_NOTICE_BOARD;
CREATE SEQUENCE SEQ_NOTICE_BOARD START WITH 1 INCREMENT BY 1;

-- ANSWER
DROP SEQUENCE SEQ_ANSWER;
CREATE SEQUENCE SEQ_ANSWER START WITH 1 INCREMENT BY 1;

-- INVENTORY
DROP SEQUENCE SEQ_INVENTORY;
CREATE SEQUENCE SEQ_INVENTORY START WITH 1 INCREMENT BY 1;

-- MATERIAL_INOUT
DROP SEQUENCE SEQ_MATERIAL_INOUT;
CREATE SEQUENCE SEQ_MATERIAL_INOUT START WITH 1 INCREMENT BY 1;

-- PRODUCTION_PLAN
DROP SEQUENCE SEQ_PRODUCTION_PLAN;
CREATE SEQUENCE SEQ_PRODUCTION_PLAN START WITH 1 INCREMENT BY 1;

-- WORK_ORDER
DROP SEQUENCE SEQ_WORK_ORDER;
CREATE SEQUENCE SEQ_WORK_ORDER START WITH 1 INCREMENT BY 1;

-- PRODUCTION_RESULT
DROP SEQUENCE SEQ_PRODUCTION_RESULT;
CREATE SEQUENCE SEQ_PRODUCTION_RESULT START WITH 1 INCREMENT BY 1;

-- FINAL_INSPECTION
DROP SEQUENCE SEQ_FINAL_INSPECTION;
CREATE SEQUENCE SEQ_FINAL_INSPECTION START WITH 1 INCREMENT BY 1;

-- DEFECT_PRODUCT
DROP SEQUENCE SEQ_DEFECT_PRODUCT;
CREATE SEQUENCE SEQ_DEFECT_PRODUCT START WITH 1 INCREMENT BY 1;

-- MATERIAL_INSPECTION
DROP SEQUENCE SEQ_MATERIAL_INSPECTION;
CREATE SEQUENCE SEQ_MATERIAL_INSPECTION START WITH 1 INCREMENT BY 1;

-- DEFECT_MATERIAL
DROP SEQUENCE SEQ_DEFECT_MATERIAL;
CREATE SEQUENCE SEQ_DEFECT_MATERIAL START WITH 1 INCREMENT BY 1;

-- BOM
DROP SEQUENCE SEQ_BOM;
CREATE SEQUENCE SEQ_BOM START WITH 1 INCREMENT BY 1;

-- BOM_DETAIL
DROP SEQUENCE SEQ_BOM_DETAIL;
CREATE SEQUENCE SEQ_BOM_DETAIL START WITH 1 INCREMENT BY 1;

-- ROUTING
DROP SEQUENCE SEQ_ROUTING;
CREATE SEQUENCE SEQ_ROUTING START WITH 1 INCREMENT BY 1;

-- EQUIPMENT_MAINTENANCE
DROP SEQUENCE SEQ_EQUIPMENT_MAINTENANCE;
CREATE SEQUENCE SEQ_EQUIPMENT_MAINTENANCE START WITH 1 INCREMENT BY 1;

-- EQUIPMENT_FAILURE_ACTION
DROP SEQUENCE SEQ_EQUIPMENT_FAILURE_ACTION;
CREATE SEQUENCE SEQ_EQUIPMENT_FAILURE_ACTION START WITH 1 INCREMENT BY 1;

COMMIT;