-- =========================================================
-- BOARD DUMMY 20 EACH
-- NOTICE_BOARD / SUGGESTION_BOARD / ANSWER
-- FK-safe by EMP_NO / SUGGESTION TITLE lookup
-- =========================================================

-- =========================================================
-- NOTICE_BOARD : 20 rows
-- =========================================================
INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '시스템 정기 점검 안내', '2026년 4월 11일 22시부터 23시까지 MES 정기 점검이 진행됩니다. 점검 시간 동안 일부 메뉴 접근이 제한될 수 있습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'), '게시중', 128, '운영 공지',
       TO_DATE('2026-04-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '시스템 정기 점검 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '비밀번호 변경 정책 안내', '보안 강화를 위해 최초 로그인 후 반드시 비밀번호를 변경해야 합니다. 비밀번호는 영문, 숫자, 특수문자를 포함해 설정해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'), '게시중', 96, '보안 공지',
       TO_DATE('2026-04-10 09:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 09:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '비밀번호 변경 정책 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '생산 계획 등록 마감 시간 공지', '당일 생산 계획은 매일 오전 10시 이전까지 등록을 완료해주세요. 이후 등록 건은 익일 계획으로 반영될 수 있습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'), '게시중', 84, '생산 협조 요청',
       TO_DATE('2026-04-10 09:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 09:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '생산 계획 등록 마감 시간 공지');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '자재 입고 처리 기준 변경 안내', '입고 완료 처리 전 자재 검사 의뢰 등록을 먼저 진행하도록 프로세스가 변경되었습니다. 담당 부서는 업무에 참고해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25009'), '게시중', 75, '자재 공지',
       TO_DATE('2026-04-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25009')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '자재 입고 처리 기준 변경 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '완제품 검사 성적서 보관 규정', '완제품 검사 성적서는 발행일 기준으로 지정 폴더에 저장하고, 파일명은 LOT 번호 기준으로 관리해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'), '게시중', 63, '품질 문서 관리',
       TO_DATE('2026-04-10 10:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '완제품 검사 성적서 보관 규정');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '설비 점검 체크리스트 업데이트', '혼합 및 분쇄 설비의 일상 점검 체크리스트가 업데이트되었습니다. 최신 양식을 확인 후 사용해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25017'), '게시중', 58, '설비 점검',
       TO_DATE('2026-04-10 10:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25017')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '설비 점검 체크리스트 업데이트');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, 'LOT 추적 조회 기능 개선 예정', 'LOT 기준 이력 조회 화면의 검색 속도 개선 작업이 예정되어 있습니다. 반영 일정은 추후 재공지하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'), '게시중', 47, '개선 예정',
       TO_DATE('2026-04-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = 'LOT 추적 조회 기능 개선 예정');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '라인별 작업 현황 집계 기준 안내', '작업 현황 화면의 진행률은 작업지시 수량 대비 실적 반영 기준으로 계산됩니다. 사용자 참고 바랍니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'), '게시중', 55, '화면 안내',
       TO_DATE('2026-04-10 11:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '라인별 작업 현황 집계 기준 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, 'BOM 버전 관리 유의사항', '동일 품목의 BOM은 최신 버전만 사용 처리하고, 이전 버전은 비활성화 상태로 유지해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25016'), '게시중', 42, '기준정보 관리',
       TO_DATE('2026-04-10 11:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25016')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = 'BOM 버전 관리 유의사항');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '출하 전 최종 검사 필수 안내', '완제품 출하 전에는 반드시 최종 검사 완료 상태를 확인한 뒤 출하 준비를 진행해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'), '게시중', 61, '출하 품질 공지',
       TO_DATE('2026-04-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '출하 전 최종 검사 필수 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '재고 부족 품목 우선 발주 요청', '안전재고 이하로 내려간 원자재는 우선 발주 검토 대상입니다. 자재팀은 재고 현황을 수시 확인해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25009'), '게시중', 69, '재고 관리',
       TO_DATE('2026-04-10 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 13:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25009')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '재고 부족 품목 우선 발주 요청');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '설비 비가동 사유 등록 협조', '설비 정지 발생 시 비가동 사유와 조치 내역을 당일 기준으로 반드시 등록해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25017'), '게시중', 44, '설비 이력 관리',
       TO_DATE('2026-04-10 13:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 13:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25017')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '설비 비가동 사유 등록 협조');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '작업지시 비고란 작성 기준', '작업지시 등록 시 특이사항, 긴급 오더, 검사 연계 여부 등은 비고란에 간단히 남겨주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25016'), '게시중', 38, '작업관리 안내',
       TO_DATE('2026-04-10 13:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 13:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25016')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '작업지시 비고란 작성 기준');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '공정검사 결과 입력 시간 준수', '공정검사 결과는 검사 완료 즉시 등록해주시고, 지연 등록으로 인한 누락이 없도록 협조 바랍니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'), '게시중', 33, '품질 운영',
       TO_DATE('2026-04-10 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 14:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '공정검사 결과 입력 시간 준수');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, 'MES 공통 코드 사용 규칙', '문서번호, 품목코드, 불량코드 등은 확정된 코드체계 기준으로만 사용해주세요. 임의 생성은 금지합니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'), '게시중', 71, '코드체계 준수',
       TO_DATE('2026-04-10 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 14:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = 'MES 공통 코드 사용 규칙');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '원자재 로케이션 표기 통일', '로케이션 표기는 LOC-WH-RM-01-A01 형식으로 통일합니다. 엑셀 및 시스템 입력 시 동일 기준을 지켜주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25009'), '게시중', 40, '창고 표기 기준',
       TO_DATE('2026-04-10 14:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 14:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25009')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '원자재 로케이션 표기 통일');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '생산 실적 등록 누락 점검 안내', '당일 종료된 작업지시는 실적 등록 누락 여부를 퇴근 전 한번 더 점검해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25016'), '게시중', 52, '실적 마감',
       TO_DATE('2026-04-10 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 15:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25016')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '생산 실적 등록 누락 점검 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '공지사항 조회수 초기화 정책 없음', '공지사항 조회수는 누적 관리되며 별도 초기화 정책은 없습니다. 테스트 시 참고 바랍니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'), '게시중', 27, '운영 기준',
       TO_DATE('2026-04-10 15:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 15:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '공지사항 조회수 초기화 정책 없음');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '검사 불합격 건 재작업 프로세스 안내', '불합격 판정 건은 관련 부서와 협의 후 재작업 또는 폐기 처리 절차를 진행해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'), '게시중', 49, '불합격 처리',
       TO_DATE('2026-04-10 15:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 15:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '검사 불합격 건 재작업 프로세스 안내');

INSERT INTO NOTICE_BOARD (NOTICE_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_NOTICE_BOARD.NEXTVAL, '월말 데이터 점검 일정 안내', '월말에는 주요 마스터 데이터와 생산 실적 데이터 정합성 점검이 예정되어 있습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'), '게시중', 36, '월말 점검',
       TO_DATE('2026-04-10 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 16:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (SELECT 1 FROM NOTICE_BOARD WHERE TITLE = '월말 데이터 점검 일정 안내');

-- =========================================================
-- SUGGESTION_BOARD : 20 rows
-- =========================================================
INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '자재 입고 화면 검색 조건 개선 요청', '입고 화면에서 품목코드와 품목명을 동시에 검색할 수 있으면 조회 속도가 더 빨라질 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25008'), '접수', 32, '자재팀 건의',
       TO_DATE('2026-04-10 09:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 09:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25008')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '자재 입고 화면 검색 조건 개선 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '재고 부족 품목 색상 표시 요청', '안전재고 이하 품목은 빨간색 또는 경고 아이콘으로 표시되면 한눈에 파악하기 좋겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25007'), '답변완료', 29, '재고 가시성 개선',
       TO_DATE('2026-04-10 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 09:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25007')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '재고 부족 품목 색상 표시 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '생산계획 엑셀 업로드 기능 제안', '생산계획을 일괄 등록할 수 있도록 엑셀 업로드 기능이 있으면 반복 입력 시간이 줄어들 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25016'), '검토중', 41, '생산팀 요청',
       TO_DATE('2026-04-10 09:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 09:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25016')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '생산계획 엑셀 업로드 기능 제안');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '작업지시 화면 공정 필터 추가 요청', '작업지시 조회 시 공정별 필터가 추가되면 담당 공정만 빠르게 확인할 수 있을 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25014'), '접수', 18, '현장 작업자 요청',
       TO_DATE('2026-04-10 10:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25014')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '작업지시 화면 공정 필터 추가 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '완제품 검사 성적서 자동 파일명 기능', '성적서 저장 시 LOT 번호 기준으로 파일명이 자동 입력되면 문서 관리가 편할 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25015'), '답변완료', 22, '품질 문서 편의성',
       TO_DATE('2026-04-10 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25015')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '완제품 검사 성적서 자동 파일명 기능');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '설비 비가동 이력 그래프 제공 요청', '설비별 비가동 시간을 월 단위 그래프로 보여주면 관리자가 추세를 보기 좋겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25013'), '검토중', 26, '설비 통계 개선',
       TO_DATE('2026-04-10 10:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25013')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '설비 비가동 이력 그래프 제공 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '공지사항 상단 고정 기능 요청', '중요 공지는 일정 기간 동안 목록 상단에 고정 표시되면 좋겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25004'), '접수', 15, '공지 기능 개선',
       TO_DATE('2026-04-10 11:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25004')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '공지사항 상단 고정 기능 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '건의사항 처리상태 세분화 제안', '접수, 검토중, 반영완료, 보류처럼 처리상태를 조금 더 자세히 나누면 확인하기 편할 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'), '검토중', 19, '게시판 상태 개선',
       TO_DATE('2026-04-10 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '건의사항 처리상태 세분화 제안');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '자재 검사 결과 조회 정렬 기준 추가', '검사일 최신순 외에도 품목코드순으로 정렬할 수 있으면 확인이 수월합니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25006'), '접수', 14, '품질 조회 개선',
       TO_DATE('2026-04-10 11:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25006')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '자재 검사 결과 조회 정렬 기준 추가');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, 'LOT 추적 화면에서 기간 기본값 요청', 'LOT 추적 조회 시 최근 7일을 기본값으로 잡아주면 사용이 더 편할 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'), '답변완료', 24, '조회 편의성',
       TO_DATE('2026-04-10 12:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 12:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = 'LOT 추적 화면에서 기간 기본값 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, 'BOM 변경 이력 별도 표시 제안', 'BOM 버전이 바뀌었을 때 변경된 항목을 한눈에 볼 수 있는 이력 화면이 필요합니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'), '검토중', 31, '기준정보 관리',
       TO_DATE('2026-04-10 13:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 13:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = 'BOM 변경 이력 별도 표시 제안');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '생산실적 등록 시 계획 대비 차이 자동계산', '실적 입력 시 계획 대비 증감 수량이 자동으로 보여지면 입력 확인에 도움이 됩니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25005'), '접수', 17, '실적 화면 개선',
       TO_DATE('2026-04-10 13:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 13:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25005')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '생산실적 등록 시 계획 대비 차이 자동계산');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '설비 점검 예정일 알림 기능 요청', '다음 점검 예정일이 가까워지면 메인 화면 또는 팝업으로 알림이 나오면 좋겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25003'), '검토중', 20, '예방보전 요청',
       TO_DATE('2026-04-10 13:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 13:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25003')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '설비 점검 예정일 알림 기능 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '재고 조회 화면 위치 정보 표시 확대', '현재 위치 정보가 짧게 보여서 불편합니다. 로케이션 전체를 보이게 해주세요.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25002'), '접수', 13, '창고 조회 개선',
       TO_DATE('2026-04-10 14:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 14:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25002')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '재고 조회 화면 위치 정보 표시 확대');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '불량코드 조회 시 분류 필터 추가', '불량코드를 자재, 공정, 완제품 기준으로 필터링할 수 있으면 찾기 쉬울 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25011'), '답변완료', 28, '불량관리 개선',
       TO_DATE('2026-04-10 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 14:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25011')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '불량코드 조회 시 분류 필터 추가');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '생산라인별 대시보드 위젯 추가 요청', '라인별 진행률과 비가동 현황을 카드형으로 보여주는 위젯이 있으면 좋겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25001'), '검토중', 35, '대시보드 고도화',
       TO_DATE('2026-04-10 14:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 14:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25001')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '생산라인별 대시보드 위젯 추가 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '모달 창 닫기 버튼 위치 통일 요청', '등록과 상세보기 모달의 닫기 버튼 위치가 같으면 사용성이 더 좋아질 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'), '접수', 12, 'UI 통일성',
       TO_DATE('2026-04-10 15:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 15:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '모달 창 닫기 버튼 위치 통일 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '작업현황 진행률 반영 기준 설명 필요', '진행률 계산 방식이 화면에 설명되면 신규 사용자도 이해하기 쉬울 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25014'), '검토중', 16, '화면 가이드',
       TO_DATE('2026-04-10 15:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 15:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25014')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '작업현황 진행률 반영 기준 설명 필요');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '품목 마스터 비고 길이 확대 요청', '비고란에 조금 더 상세 내용을 남길 수 있도록 입력 길이를 넉넉히 쓰고 싶습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25009'), '접수', 11, '마스터 관리',
       TO_DATE('2026-04-10 15:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 15:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25009')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '품목 마스터 비고 길이 확대 요청');

INSERT INTO SUGGESTION_BOARD (SUGGESTION_ID, TITLE, CONTENT, WRITER_EMP_ID, STATUS, VIEW_COUNT, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUGGESTION_BOARD.NEXTVAL, '메뉴 권한별 숨김 처리 강화 제안', '권한이 없는 사용자는 메뉴 자체가 보이지 않게 하면 더 직관적일 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25017'), '답변완료', 23, '권한 관리',
       TO_DATE('2026-04-10 16:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 16:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25017')
  AND NOT EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '메뉴 권한별 숨김 처리 강화 제안');

-- =========================================================
-- ANSWER : 20 rows
-- =========================================================
INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '자재 입고 화면 검색 조건 개선 요청'),
       '의견 확인했습니다. 다음 화면 개선 작업 때 품목코드와 품목명 동시 검색 기능을 우선 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '운영팀 검토 예정',
       TO_DATE('2026-04-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '자재 입고 화면 검색 조건 개선 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '자재 입고 화면 검색 조건 개선 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('의견 확인했습니다. 다음 화면 개선 작업 때 품목코드와 품목명 동시 검색 기능을 우선 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '재고 부족 품목 색상 표시 요청'),
       '반영 가능합니다. 안전재고 이하 품목은 경고 색상으로 구분되도록 수정 목록에 추가하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '반영 예정',
       TO_DATE('2026-04-10 10:05:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:05:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '재고 부족 품목 색상 표시 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '재고 부족 품목 색상 표시 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('반영 가능합니다. 안전재고 이하 품목은 경고 색상으로 구분되도록 수정 목록에 추가하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '생산계획 엑셀 업로드 기능 제안'),
       '기능 필요성은 공감합니다. 다만 현재 일정상 2차 범위 이후로 검토가 필요합니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'),
       '등록', '차기 개선 과제',
       TO_DATE('2026-04-10 10:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '생산계획 엑셀 업로드 기능 제안')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '생산계획 엑셀 업로드 기능 제안'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('기능 필요성은 공감합니다. 다만 현재 일정상 2차 범위 이후로 검토가 필요합니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '작업지시 화면 공정 필터 추가 요청'),
       '작업지시 조회 조건에 공정 필터를 추가하는 방향으로 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'),
       '등록', '검토중',
       TO_DATE('2026-04-10 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:15:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '작업지시 화면 공정 필터 추가 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '작업지시 화면 공정 필터 추가 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('작업지시 조회 조건에 공정 필터를 추가하는 방향으로 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '완제품 검사 성적서 자동 파일명 기능'),
       '파일명 자동 생성 규칙은 적용 가능해 보입니다. LOT 번호 기준으로 연결되도록 설계하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'),
       '등록', '품질팀 협의 완료',
       TO_DATE('2026-04-10 10:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '완제품 검사 성적서 자동 파일명 기능')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '완제품 검사 성적서 자동 파일명 기능'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('파일명 자동 생성 규칙은 적용 가능해 보입니다. LOT 번호 기준으로 연결되도록 설계하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '설비 비가동 이력 그래프 제공 요청'),
       '대시보드 확장 시 설비 통계 그래프 영역에 포함할 수 있도록 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25017'),
       '등록', '설비팀 요청 반영',
       TO_DATE('2026-04-10 10:25:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:25:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '설비 비가동 이력 그래프 제공 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25017')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '설비 비가동 이력 그래프 제공 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('대시보드 확장 시 설비 통계 그래프 영역에 포함할 수 있도록 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '공지사항 상단 고정 기능 요청'),
       '중요 공지 고정 기능은 활용도가 높아 보여 우선순위를 높게 두고 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', 'UI 개선 검토',
       TO_DATE('2026-04-10 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '공지사항 상단 고정 기능 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '공지사항 상단 고정 기능 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('중요 공지 고정 기능은 활용도가 높아 보여 우선순위를 높게 두고 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '건의사항 처리상태 세분화 제안'),
       '상태값 세분화는 좋은 의견입니다. 다만 현재 ERD 상태 컬럼 범위 내에서 운영 가능 여부를 먼저 보겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '운영 기준 검토',
       TO_DATE('2026-04-10 10:35:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:35:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '건의사항 처리상태 세분화 제안')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '건의사항 처리상태 세분화 제안'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('상태값 세분화는 좋은 의견입니다. 다만 현재 ERD 상태 컬럼 범위 내에서 운영 가능 여부를 먼저 보겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '자재 검사 결과 조회 정렬 기준 추가'),
       '정렬 옵션 추가는 구현 난이도가 높지 않아 빠르게 반영 가능할 것 같습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'),
       '등록', '빠른 반영 가능',
       TO_DATE('2026-04-10 10:40:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:40:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '자재 검사 결과 조회 정렬 기준 추가')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '자재 검사 결과 조회 정렬 기준 추가'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('정렬 옵션 추가는 구현 난이도가 높지 않아 빠르게 반영 가능할 것 같습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = 'LOT 추적 화면에서 기간 기본값 요청'),
       '최근 7일 기본값 설정은 사용성 개선에 도움이 되어 반영하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '반영 예정',
       TO_DATE('2026-04-10 10:45:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:45:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = 'LOT 추적 화면에서 기간 기본값 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = 'LOT 추적 화면에서 기간 기본값 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('최근 7일 기본값 설정은 사용성 개선에 도움이 되어 반영하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = 'BOM 변경 이력 별도 표시 제안'),
       '버전 변경 이력 화면은 필요성이 높습니다. BOM 상세 확장 시 함께 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'),
       '등록', '차기 고도화',
       TO_DATE('2026-04-10 10:50:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:50:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = 'BOM 변경 이력 별도 표시 제안')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = 'BOM 변경 이력 별도 표시 제안'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('버전 변경 이력 화면은 필요성이 높습니다. BOM 상세 확장 시 함께 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '생산실적 등록 시 계획 대비 차이 자동계산'),
       '실적 화면에서 자동 계산되도록 수정하면 오류 예방에 도움이 될 것 같습니다. 반영 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'),
       '등록', '생산팀 의견 반영',
       TO_DATE('2026-04-10 10:55:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 10:55:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '생산실적 등록 시 계획 대비 차이 자동계산')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '생산실적 등록 시 계획 대비 차이 자동계산'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('실적 화면에서 자동 계산되도록 수정하면 오류 예방에 도움이 될 것 같습니다. 반영 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '설비 점검 예정일 알림 기능 요청'),
       '알림 기능은 유용하지만 현재 범위에서는 우선순위가 낮습니다. 추후 일정에 포함해보겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25017'),
       '등록', '보류',
       TO_DATE('2026-04-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '설비 점검 예정일 알림 기능 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25017')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '설비 점검 예정일 알림 기능 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('알림 기능은 유용하지만 현재 범위에서는 우선순위가 낮습니다. 추후 일정에 포함해보겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '재고 조회 화면 위치 정보 표시 확대'),
       '화면 폭을 고려해 위치 정보 전체가 보이도록 컬럼 크기와 툴팁 방식을 같이 보겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25009'),
       '등록', '조회 화면 개선',
       TO_DATE('2026-04-10 11:05:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:05:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '재고 조회 화면 위치 정보 표시 확대')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25009')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '재고 조회 화면 위치 정보 표시 확대'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('화면 폭을 고려해 위치 정보 전체가 보이도록 컬럼 크기와 툴팁 방식을 같이 보겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '불량코드 조회 시 분류 필터 추가'),
       '불량 분류 필터는 새 코드체계와도 맞아서 우선 적용 대상으로 보겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25018'),
       '등록', '코드체계 반영',
       TO_DATE('2026-04-10 11:10:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:10:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '불량코드 조회 시 분류 필터 추가')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25018')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '불량코드 조회 시 분류 필터 추가'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('불량 분류 필터는 새 코드체계와도 맞아서 우선 적용 대상으로 보겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '생산라인별 대시보드 위젯 추가 요청'),
       '대시보드 시각화 영역 확장 시 참고하겠습니다. 라인별 카드 형태는 좋은 방향입니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'),
       '등록', '대시보드 개선안',
       TO_DATE('2026-04-10 11:15:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:15:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '생산라인별 대시보드 위젯 추가 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '생산라인별 대시보드 위젯 추가 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('대시보드 시각화 영역 확장 시 참고하겠습니다. 라인별 카드 형태는 좋은 방향입니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '모달 창 닫기 버튼 위치 통일 요청'),
       'UI 통일성 측면에서 맞는 의견입니다. 모달 공통 컴포넌트 수정 시 반영하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '공통 UI 반영',
       TO_DATE('2026-04-10 11:20:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:20:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '모달 창 닫기 버튼 위치 통일 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '모달 창 닫기 버튼 위치 통일 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('UI 통일성 측면에서 맞는 의견입니다. 모달 공통 컴포넌트 수정 시 반영하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '작업현황 진행률 반영 기준 설명 필요'),
       '진행률 산정 기준 문구를 화면 하단 또는 도움말로 제공하는 방안을 검토하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25020'),
       '등록', '가이드 추가 검토',
       TO_DATE('2026-04-10 11:25:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:25:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '작업현황 진행률 반영 기준 설명 필요')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25020')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '작업현황 진행률 반영 기준 설명 필요'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('진행률 산정 기준 문구를 화면 하단 또는 도움말로 제공하는 방안을 검토하겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '품목 마스터 비고 길이 확대 요청'),
       '현재 컬럼 길이 범위 내에서 운영 가능 여부를 먼저 확인하고 필요 시 구조도 같이 보겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '마스터 개선 검토',
       TO_DATE('2026-04-10 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:30:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '품목 마스터 비고 길이 확대 요청')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '품목 마스터 비고 길이 확대 요청'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('현재 컬럼 길이 범위 내에서 운영 가능 여부를 먼저 확인하고 필요 시 구조도 같이 보겠습니다.')) = 0
  );

INSERT INTO ANSWER (ANSWER_ID, SUGGESTION_ID, CONTENT, WRITER_EMP_ID, STATUS, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ANSWER.NEXTVAL,
       (SELECT SUGGESTION_ID FROM SUGGESTION_BOARD WHERE TITLE = '메뉴 권한별 숨김 처리 강화 제안'),
       '권한 없는 메뉴 비노출은 사용자 경험에 도움이 됩니다. 권한 분기 로직 보완 시 반영하겠습니다.',
       (SELECT EMP_ID FROM EMP WHERE EMP_NO = 'E25019'),
       '등록', '권한 로직 검토',
       TO_DATE('2026-04-10 11:35:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-10 11:35:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUGGESTION_BOARD WHERE TITLE = '메뉴 권한별 숨김 처리 강화 제안')
  AND EXISTS (SELECT 1 FROM EMP WHERE EMP_NO = 'E25019')
  AND NOT EXISTS (
      SELECT 1
      FROM ANSWER A
      JOIN SUGGESTION_BOARD S ON A.SUGGESTION_ID = S.SUGGESTION_ID
      WHERE S.TITLE = '메뉴 권한별 숨김 처리 강화 제안'
        AND DBMS_LOB.COMPARE(A.CONTENT, TO_CLOB('권한 없는 메뉴 비노출은 사용자 경험에 도움이 됩니다. 권한 분기 로직 보완 시 반영하겠습니다.')) = 0
  );

COMMIT;