-- =========================================================
-- BeginAgain_additional_insert.sql
-- run after BeginAgain_insert.sql
-- run after BeginAgain_additional_tables.sql
-- 신규 추가 테이블 더미 데이터
-- Oracle SQL / FK-safe / rerunnable
-- =========================================================

-- ---------------------------------------------------------
-- LINE
-- ---------------------------------------------------------
INSERT INTO LINE (LINE_ID, LINE_CODE, LINE_NAME, LINE_TYPE, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_LINE.NEXTVAL, 'LN-A', '1라인', '혼합/소성', 'Y', '주력 양극재 라인 A', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-A');

INSERT INTO LINE (LINE_ID, LINE_CODE, LINE_NAME, LINE_TYPE, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_LINE.NEXTVAL, 'LN-B', '2라인', '분쇄/검사', 'Y', '주력 양극재 라인 B', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-B');

INSERT INTO LINE (LINE_ID, LINE_CODE, LINE_NAME, LINE_TYPE, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_LINE.NEXTVAL, 'LN-C', '3라인', '포장/출하', 'Y', '고객사 납기 대응 라인', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-C');

INSERT INTO LINE (LINE_ID, LINE_CODE, LINE_NAME, LINE_TYPE, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_LINE.NEXTVAL, 'LN-D', '4라인', '시험생산', 'Y', '시험 생산 및 샘플 대응', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-D');

INSERT INTO LINE (LINE_ID, LINE_CODE, LINE_NAME, LINE_TYPE, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_LINE.NEXTVAL, 'LN-E', '5라인', '예비라인', 'N', '예비 설비 라인', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-E');

-- ---------------------------------------------------------
-- CUSTOMER
-- ---------------------------------------------------------
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_CUSTOMER.NEXTVAL, 'CUST-001', '네오셀텍', '김대리', '02-4100-1001', 'neo1@client.com', '경기도 화성시 동탄산단 1로', 'Y', '주요 배터리 소재 고객사', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-001');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_CUSTOMER.NEXTVAL, 'CUST-002', '미래에너지솔루션', '박과장', '02-4100-1002', 'energy@client.com', '충청북도 청주시 오창산단 2로', 'Y', '납기 우선 고객사', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-002');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_CUSTOMER.NEXTVAL, 'CUST-003', '한빛소재', '이주임', '02-4100-1003', 'hanbit@client.com', '전라북도 군산시 자유무역로', 'Y', '소량 다품종 주문처', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-003');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_CUSTOMER.NEXTVAL, 'CUST-004', '그린파워머티리얼즈', '정차장', '02-4100-1004', 'green@client.com', '세종특별자치시 집현중앙로', 'Y', '월 단위 정기 발주', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-004');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_CUSTOMER.NEXTVAL, 'CUST-005', '리포트데모', '최담당', '02-4100-1999', 'report@client.com', '서울특별시 금천구 가산디지털로', 'Y', '리포트/대시보드 테스트용', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-005');

-- ---------------------------------------------------------
-- SUPPLIER
-- ---------------------------------------------------------
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_CODE, SUPPLIER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUPPLIER.NEXTVAL, 'SUP-001', '휴먼산업', '오현수', '031-5100-1001', 'human@vendor.com', '경기도 평택시 포승공단로', 'Y', '리튬계 원자재 공급', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-001');

INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_CODE, SUPPLIER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUPPLIER.NEXTVAL, 'SUP-002', '미래화학', '김동현', '031-5100-1002', 'mirae@vendor.com', '충청남도 아산시 음봉산단로', 'Y', '망간계 원자재 공급', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-002');

INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_CODE, SUPPLIER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUPPLIER.NEXTVAL, 'SUP-003', '케이첨가제', '문지훈', '031-5100-1003', 'kadd@vendor.com', '충청북도 진천군 산수산단로', 'Y', '첨가제 공급 업체', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-003');

INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_CODE, SUPPLIER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUPPLIER.NEXTVAL, 'SUP-004', '대한시스템', '최영민', '031-5100-1004', 'daehan@vendor.com', '경기도 안산시 단원구 산단로', 'Y', '설비 및 부자재 협력사', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-004');

INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_CODE, SUPPLIER_NAME, MANAGER_NAME, PHONE, EMAIL, ADDRESS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SUPPLIER.NEXTVAL, 'SUP-005', '에이치테크', '서민재', '031-5100-1005', 'htech@vendor.com', '대전광역시 유성구 테크노로', 'Y', '검사장비 협력사', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-005');

-- ---------------------------------------------------------
-- WAREHOUSE
-- ---------------------------------------------------------
INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, LOCATION, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_WAREHOUSE.NEXTVAL, 'WH-RM-001', '원자재창고 1동', '원자재', 'A동 1층', 'Y', '리튬/망간 원자재 보관', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSE WHERE WAREHOUSE_CODE = 'WH-RM-001');

INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, LOCATION, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_WAREHOUSE.NEXTVAL, 'WH-IP-001', '공정재창고', '반제품', 'B동 1층', 'Y', '공정 대기품 보관', TO_DATE('2026-04-11', 'YYYY-MM-DD'), TO_DATE('2026-04-11', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSE WHERE WAREHOUSE_CODE = 'WH-IP-001');

INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, LOCATION, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_WAREHOUSE.NEXTVAL, 'WH-FG-001', '완제품창고 1동', '완제품', 'C동 2층', 'Y', '출하 대기 완제품 보관', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSE WHERE WAREHOUSE_CODE = 'WH-FG-001');

INSERT INTO WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, LOCATION, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_WAREHOUSE.NEXTVAL, 'WH-HOLD-001', '보류품창고', '격리', 'D동 1층', 'Y', '불합격/보류 품목 격리', TO_DATE('2026-04-12', 'YYYY-MM-DD'), TO_DATE('2026-04-12', 'YYYY-MM-DD')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSE WHERE WAREHOUSE_CODE = 'WH-HOLD-001');

-- ---------------------------------------------------------
-- SALES_ORDER
-- ---------------------------------------------------------
INSERT INTO SALES_ORDER (SALES_ORDER_ID, ORDER_NO, CUSTOMER_ID, ITEM_ID, ORDER_DATE, DUE_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, PRIORITY, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SALES_ORDER.NEXTVAL,
       'SO-202604-001',
       (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-001'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-20', 'YYYY-MM-DD'),
       4200, 12800, 53760000,
       '등록', '상', 'Y', '네오셀텍 4월 1차 발주', TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-13', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-001')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND NOT EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-001');

INSERT INTO SALES_ORDER (SALES_ORDER_ID, ORDER_NO, CUSTOMER_ID, ITEM_ID, ORDER_DATE, DUE_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, PRIORITY, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SALES_ORDER.NEXTVAL,
       'SO-202604-002',
       (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-002'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002'),
       TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-21', 'YYYY-MM-DD'),
       3800, 13500, 51300000,
       '진행중', '중', 'Y', '미래에너지솔루션 납기 우선 건', TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-13', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-002')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
  AND NOT EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-002');

INSERT INTO SALES_ORDER (SALES_ORDER_ID, ORDER_NO, CUSTOMER_ID, ITEM_ID, ORDER_DATE, DUE_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, PRIORITY, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SALES_ORDER.NEXTVAL,
       'SO-202604-003',
       (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-003'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003'),
       TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-22', 'YYYY-MM-DD'),
       2500, 17400, 43500000,
       '등록', '중', 'Y', '소량 긴급 발주', TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-14', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-003')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003')
  AND NOT EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-003');

INSERT INTO SALES_ORDER (SALES_ORDER_ID, ORDER_NO, CUSTOMER_ID, ITEM_ID, ORDER_DATE, DUE_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, PRIORITY, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SALES_ORDER.NEXTVAL,
       'SO-202604-004',
       (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-004'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-24', 'YYYY-MM-DD'),
       3100, 12950, 40145000,
       '진행중', '하', 'Y', '정기 월간 발주', TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-14', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-004')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND NOT EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-004');

INSERT INTO SALES_ORDER (SALES_ORDER_ID, ORDER_NO, CUSTOMER_ID, ITEM_ID, ORDER_DATE, DUE_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, PRIORITY, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SALES_ORDER.NEXTVAL,
       'SO-202604-005',
       (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-005'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-25', 'YYYY-MM-DD'),
       2000, 12600, 25200000,
       '등록', '중', 'Y', '대시보드 테스트 발주 1', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-005')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND NOT EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-005');

INSERT INTO SALES_ORDER (SALES_ORDER_ID, ORDER_NO, CUSTOMER_ID, ITEM_ID, ORDER_DATE, DUE_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, PRIORITY, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SALES_ORDER.NEXTVAL,
       'SO-202604-006',
       (SELECT CUSTOMER_ID FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-005'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002'),
       TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-26', 'YYYY-MM-DD'),
       2100, 13300, 27930000,
       '등록', '중', 'Y', '대시보드 테스트 발주 2', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM CUSTOMER WHERE CUSTOMER_CODE = 'CUST-005')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
  AND NOT EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-006');

-- ---------------------------------------------------------
-- SHIPMENT
-- ---------------------------------------------------------
INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, SALES_ORDER_ID, ITEM_ID, LOT_NO, SHIP_DATE, DUE_DATE, SHIP_QTY, ON_TIME_YN, STATUS, DELAY_REASON, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SHIPMENT.NEXTVAL,
       'SHP-202604-001',
       (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-001'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       'LOT-FG-CAM-001-A01',
       TO_DATE('2026-04-19', 'YYYY-MM-DD'), TO_DATE('2026-04-20', 'YYYY-MM-DD'),
       4200, 'Y', '출하완료', NULL, 'Y', '정상 출하', TO_DATE('2026-04-19', 'YYYY-MM-DD'), TO_DATE('2026-04-19', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-001')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND NOT EXISTS (SELECT 1 FROM SHIPMENT WHERE SHIPMENT_NO = 'SHP-202604-001');

INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, SALES_ORDER_ID, ITEM_ID, LOT_NO, SHIP_DATE, DUE_DATE, SHIP_QTY, ON_TIME_YN, STATUS, DELAY_REASON, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SHIPMENT.NEXTVAL,
       'SHP-202604-002',
       (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-002'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002'),
       'LOT-FG-CAM-002-B01',
       TO_DATE('2026-04-22', 'YYYY-MM-DD'), TO_DATE('2026-04-21', 'YYYY-MM-DD'),
       3600, 'N', '부분출하', '설비 점검으로 일부 지연', 'Y', '납기 지연 테스트', TO_DATE('2026-04-22', 'YYYY-MM-DD'), TO_DATE('2026-04-22', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-002')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
  AND NOT EXISTS (SELECT 1 FROM SHIPMENT WHERE SHIPMENT_NO = 'SHP-202604-002');

INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, SALES_ORDER_ID, ITEM_ID, LOT_NO, SHIP_DATE, DUE_DATE, SHIP_QTY, ON_TIME_YN, STATUS, DELAY_REASON, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SHIPMENT.NEXTVAL,
       'SHP-202604-003',
       (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-003'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003'),
       'LOT-FG-CAM-003-C01',
       TO_DATE('2026-04-22', 'YYYY-MM-DD'), TO_DATE('2026-04-22', 'YYYY-MM-DD'),
       2500, 'Y', '출하완료', NULL, 'Y', '긴급건 정상 출하', TO_DATE('2026-04-22', 'YYYY-MM-DD'), TO_DATE('2026-04-22', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-003')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003')
  AND NOT EXISTS (SELECT 1 FROM SHIPMENT WHERE SHIPMENT_NO = 'SHP-202604-003');

INSERT INTO SHIPMENT (SHIPMENT_ID, SHIPMENT_NO, SALES_ORDER_ID, ITEM_ID, LOT_NO, SHIP_DATE, DUE_DATE, SHIP_QTY, ON_TIME_YN, STATUS, DELAY_REASON, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_SHIPMENT.NEXTVAL,
       'SHP-202604-004',
       (SELECT SALES_ORDER_ID FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-004'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       'LOT-FG-CAM-001-A02',
       TO_DATE('2026-04-23', 'YYYY-MM-DD'), TO_DATE('2026-04-24', 'YYYY-MM-DD'),
       3100, 'Y', '출하완료', NULL, 'Y', '정기 발주 출하', TO_DATE('2026-04-23', 'YYYY-MM-DD'), TO_DATE('2026-04-23', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SALES_ORDER WHERE ORDER_NO = 'SO-202604-004')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND NOT EXISTS (SELECT 1 FROM SHIPMENT WHERE SHIPMENT_NO = 'SHP-202604-004');

-- ---------------------------------------------------------
-- PURCHASE_ORDER
-- ---------------------------------------------------------
INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, PURCHASE_NO, SUPPLIER_ID, ITEM_ID, ORDER_DATE, EXPECTED_IN_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_PURCHASE_ORDER.NEXTVAL,
       'PO-202604-001',
       (SELECT SUPPLIER_ID FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-001'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'RM-LI-002'),
       TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-18', 'YYYY-MM-DD'),
       3000, 18200, 54600000,
       '발주완료', 'Y', '리튬염 4월 1차 발주', TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-13', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-001')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'RM-LI-002')
  AND NOT EXISTS (SELECT 1 FROM PURCHASE_ORDER WHERE PURCHASE_NO = 'PO-202604-001');

INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, PURCHASE_NO, SUPPLIER_ID, ITEM_ID, ORDER_DATE, EXPECTED_IN_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_PURCHASE_ORDER.NEXTVAL,
       'PO-202604-002',
       (SELECT SUPPLIER_ID FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-001'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'RM-LI-003'),
       TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-19', 'YYYY-MM-DD'),
       1800, 19500, 35100000,
       '입고대기', 'Y', '첨가 리튬염 확보', TO_DATE('2026-04-13', 'YYYY-MM-DD'), TO_DATE('2026-04-13', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-001')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'RM-LI-003')
  AND NOT EXISTS (SELECT 1 FROM PURCHASE_ORDER WHERE PURCHASE_NO = 'PO-202604-002');

INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, PURCHASE_NO, SUPPLIER_ID, ITEM_ID, ORDER_DATE, EXPECTED_IN_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_PURCHASE_ORDER.NEXTVAL,
       'PO-202604-003',
       (SELECT SUPPLIER_ID FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-002'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'RM-MN-001'),
       TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-20', 'YYYY-MM-DD'),
       2500, 14300, 35750000,
       '발주완료', 'Y', '주원료 보충 발주', TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-14', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-002')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'RM-MN-001')
  AND NOT EXISTS (SELECT 1 FROM PURCHASE_ORDER WHERE PURCHASE_NO = 'PO-202604-003');

INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, PURCHASE_NO, SUPPLIER_ID, ITEM_ID, ORDER_DATE, EXPECTED_IN_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_PURCHASE_ORDER.NEXTVAL,
       'PO-202604-004',
       (SELECT SUPPLIER_ID FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-002'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'RM-MN-002'),
       TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-21', 'YYYY-MM-DD'),
       2200, 13800, 30360000,
       '입고지연', 'Y', '운송 지연 모니터링 대상', TO_DATE('2026-04-14', 'YYYY-MM-DD'), TO_DATE('2026-04-14', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-002')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'RM-MN-002')
  AND NOT EXISTS (SELECT 1 FROM PURCHASE_ORDER WHERE PURCHASE_NO = 'PO-202604-004');

INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, PURCHASE_NO, SUPPLIER_ID, ITEM_ID, ORDER_DATE, EXPECTED_IN_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_PURCHASE_ORDER.NEXTVAL,
       'PO-202604-005',
       (SELECT SUPPLIER_ID FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-003'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'RM-AD-001'),
       TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-19', 'YYYY-MM-DD'),
       900, 12800, 11520000,
       '발주완료', 'Y', '바인더 첨가제 확보', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-003')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'RM-AD-001')
  AND NOT EXISTS (SELECT 1 FROM PURCHASE_ORDER WHERE PURCHASE_NO = 'PO-202604-005');

INSERT INTO PURCHASE_ORDER (PURCHASE_ORDER_ID, PURCHASE_NO, SUPPLIER_ID, ITEM_ID, ORDER_DATE, EXPECTED_IN_DATE, ORDER_QTY, UNIT_PRICE, TOTAL_AMOUNT, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_PURCHASE_ORDER.NEXTVAL,
       'PO-202604-006',
       (SELECT SUPPLIER_ID FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-003'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'RM-AD-002'),
       TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-20', 'YYYY-MM-DD'),
       700, 13500, 9450000,
       '입고완료', 'Y', '분산제 선반입', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM SUPPLIER WHERE SUPPLIER_CODE = 'SUP-003')
  AND EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'RM-AD-002')
  AND NOT EXISTS (SELECT 1 FROM PURCHASE_ORDER WHERE PURCHASE_NO = 'PO-202604-006');

-- ---------------------------------------------------------
-- EQUIPMENT_DOWNTIME
-- ---------------------------------------------------------
INSERT INTO EQUIPMENT_DOWNTIME (DOWNTIME_ID, EQUIPMENT_ID, LINE_ID, WORK_ORDER_ID, START_TIME, END_TIME, DOWNTIME_MIN, DOWNTIME_TYPE, CAUSE_CODE, CAUSE_DETAIL, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_EQUIPMENT_DOWNTIME.NEXTVAL,
       (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-TRS-003'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-C'),
       NULL,
       TO_DATE('2026-04-15 08:10:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_DATE('2026-04-15 08:42:00', 'YYYY-MM-DD HH24:MI:SS'),
       32,
       '고장', 'DT-EQ-001', '이송 모터 과열로 비가동 발생', '조치완료', 'Y', '라인C 오전 비가동', TO_DATE('2026-04-15 08:42:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-15 08:42:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-TRS-003')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-C')
  AND NOT EXISTS (
      SELECT 1 FROM EQUIPMENT_DOWNTIME
      WHERE EQUIPMENT_ID = (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-TRS-003')
        AND START_TIME = TO_DATE('2026-04-15 08:10:00', 'YYYY-MM-DD HH24:MI:SS')
  );

INSERT INTO EQUIPMENT_DOWNTIME (DOWNTIME_ID, EQUIPMENT_ID, LINE_ID, WORK_ORDER_ID, START_TIME, END_TIME, DOWNTIME_MIN, DOWNTIME_TYPE, CAUSE_CODE, CAUSE_DETAIL, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_EQUIPMENT_DOWNTIME.NEXTVAL,
       (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-QC-001'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-B'),
       NULL,
       TO_DATE('2026-04-15 10:20:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_DATE('2026-04-15 10:38:00', 'YYYY-MM-DD HH24:MI:SS'),
       18,
       '점검', 'DT-QC-001', '센서 교정 점검으로 일시 정지', '조치완료', 'Y', '검사설비 정기 점검', TO_DATE('2026-04-15 10:38:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-15 10:38:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-QC-001')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-B')
  AND NOT EXISTS (
      SELECT 1 FROM EQUIPMENT_DOWNTIME
      WHERE EQUIPMENT_ID = (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-QC-001')
        AND START_TIME = TO_DATE('2026-04-15 10:20:00', 'YYYY-MM-DD HH24:MI:SS')
  );

INSERT INTO EQUIPMENT_DOWNTIME (DOWNTIME_ID, EQUIPMENT_ID, LINE_ID, WORK_ORDER_ID, START_TIME, END_TIME, DOWNTIME_MIN, DOWNTIME_TYPE, CAUSE_CODE, CAUSE_DETAIL, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_EQUIPMENT_DOWNTIME.NEXTVAL,
       (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-CAL-001'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-A'),
       NULL,
       TO_DATE('2026-04-16 13:05:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_DATE('2026-04-16 13:47:00', 'YYYY-MM-DD HH24:MI:SS'),
       42,
       '고장', 'DT-CAL-001', '온도 편차 알람으로 소성 설비 정지', '원인분석중', 'Y', '핵심 공정 비가동', TO_DATE('2026-04-16 13:47:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-16 13:47:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-CAL-001')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-A')
  AND NOT EXISTS (
      SELECT 1 FROM EQUIPMENT_DOWNTIME
      WHERE EQUIPMENT_ID = (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-CAL-001')
        AND START_TIME = TO_DATE('2026-04-16 13:05:00', 'YYYY-MM-DD HH24:MI:SS')
  );

INSERT INTO EQUIPMENT_DOWNTIME (DOWNTIME_ID, EQUIPMENT_ID, LINE_ID, WORK_ORDER_ID, START_TIME, END_TIME, DOWNTIME_MIN, DOWNTIME_TYPE, CAUSE_CODE, CAUSE_DETAIL, STATUS, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_EQUIPMENT_DOWNTIME.NEXTVAL,
       (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-GRD-001'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-A'),
       NULL,
       TO_DATE('2026-04-17 09:30:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_DATE('2026-04-17 09:44:00', 'YYYY-MM-DD HH24:MI:SS'),
       14,
       '자재대기', 'DT-MAT-001', '분쇄 공정 투입 자재 대기', '조치완료', 'Y', '공정 간 연계 지연', TO_DATE('2026-04-17 09:44:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2026-04-17 09:44:00', 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-GRD-001')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-A')
  AND NOT EXISTS (
      SELECT 1 FROM EQUIPMENT_DOWNTIME
      WHERE EQUIPMENT_ID = (SELECT EQUIPMENT_ID FROM EQUIPMENT WHERE EQUIPMENT_CODE = 'EQ-GRD-001')
        AND START_TIME = TO_DATE('2026-04-17 09:30:00', 'YYYY-MM-DD HH24:MI:SS')
  );

-- ---------------------------------------------------------
-- STANDARD_COST
-- ---------------------------------------------------------
INSERT INTO STANDARD_COST (STANDARD_COST_ID, ITEM_ID, EFFECTIVE_FROM, EFFECTIVE_TO, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, STANDARD_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_STANDARD_COST.NEXTVAL,
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'),
       9200, 1800, 1200, 12200,
       'Y', '표준원가 2026년 기준', TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND NOT EXISTS (SELECT 1 FROM STANDARD_COST WHERE ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001') AND EFFECTIVE_FROM = TO_DATE('2026-04-01', 'YYYY-MM-DD'));

INSERT INTO STANDARD_COST (STANDARD_COST_ID, ITEM_ID, EFFECTIVE_FROM, EFFECTIVE_TO, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, STANDARD_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_STANDARD_COST.NEXTVAL,
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002'),
       TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'),
       9800, 1900, 1250, 12950,
       'Y', '표준원가 2026년 기준', TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
  AND NOT EXISTS (SELECT 1 FROM STANDARD_COST WHERE ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002') AND EFFECTIVE_FROM = TO_DATE('2026-04-01', 'YYYY-MM-DD'));

INSERT INTO STANDARD_COST (STANDARD_COST_ID, ITEM_ID, EFFECTIVE_FROM, EFFECTIVE_TO, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, STANDARD_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_STANDARD_COST.NEXTVAL,
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003'),
       TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'),
       12700, 2100, 1600, 16400,
       'Y', '표준원가 2026년 기준', TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-04-01', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003')
  AND NOT EXISTS (SELECT 1 FROM STANDARD_COST WHERE ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003') AND EFFECTIVE_FROM = TO_DATE('2026-04-01', 'YYYY-MM-DD'));

-- ---------------------------------------------------------
-- ACTUAL_COST_DAILY
-- ---------------------------------------------------------
INSERT INTO ACTUAL_COST_DAILY (ACTUAL_COST_ID, COST_DATE, ITEM_ID, LINE_ID, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, TOTAL_COST, PRODUCTION_QTY, ACTUAL_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ACTUAL_COST_DAILY.NEXTVAL,
       TO_DATE('2026-04-15', 'YYYY-MM-DD'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-A'),
       9360, 1840, 1260, 12460, 4300, 12460,
       'Y', '라인A 일일 실적원가', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-A')
  AND NOT EXISTS (
      SELECT 1 FROM ACTUAL_COST_DAILY
      WHERE COST_DATE = TO_DATE('2026-04-15', 'YYYY-MM-DD')
        AND ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
        AND LINE_ID = (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-A')
  );

INSERT INTO ACTUAL_COST_DAILY (ACTUAL_COST_ID, COST_DATE, ITEM_ID, LINE_ID, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, TOTAL_COST, PRODUCTION_QTY, ACTUAL_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ACTUAL_COST_DAILY.NEXTVAL,
       TO_DATE('2026-04-15', 'YYYY-MM-DD'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-B'),
       10020, 1940, 1290, 13250, 3950, 13250,
       'Y', '라인B 일일 실적원가', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-B')
  AND NOT EXISTS (
      SELECT 1 FROM ACTUAL_COST_DAILY
      WHERE COST_DATE = TO_DATE('2026-04-15', 'YYYY-MM-DD')
        AND ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
        AND LINE_ID = (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-B')
  );

INSERT INTO ACTUAL_COST_DAILY (ACTUAL_COST_ID, COST_DATE, ITEM_ID, LINE_ID, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, TOTAL_COST, PRODUCTION_QTY, ACTUAL_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ACTUAL_COST_DAILY.NEXTVAL,
       TO_DATE('2026-04-15', 'YYYY-MM-DD'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-C'),
       12950, 2150, 1620, 16720, 2550, 16720,
       'Y', '라인C 일일 실적원가', TO_DATE('2026-04-15', 'YYYY-MM-DD'), TO_DATE('2026-04-15', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-C')
  AND NOT EXISTS (
      SELECT 1 FROM ACTUAL_COST_DAILY
      WHERE COST_DATE = TO_DATE('2026-04-15', 'YYYY-MM-DD')
        AND ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-003')
        AND LINE_ID = (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-C')
  );

INSERT INTO ACTUAL_COST_DAILY (ACTUAL_COST_ID, COST_DATE, ITEM_ID, LINE_ID, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, TOTAL_COST, PRODUCTION_QTY, ACTUAL_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ACTUAL_COST_DAILY.NEXTVAL,
       TO_DATE('2026-04-16', 'YYYY-MM-DD'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-A'),
       9480, 1860, 1280, 12620, 4180, 12620,
       'Y', '라인A 전일대비 상승', TO_DATE('2026-04-16', 'YYYY-MM-DD'), TO_DATE('2026-04-16', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-A')
  AND NOT EXISTS (
      SELECT 1 FROM ACTUAL_COST_DAILY
      WHERE COST_DATE = TO_DATE('2026-04-16', 'YYYY-MM-DD')
        AND ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-001')
        AND LINE_ID = (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-A')
  );

INSERT INTO ACTUAL_COST_DAILY (ACTUAL_COST_ID, COST_DATE, ITEM_ID, LINE_ID, MATERIAL_COST, LABOR_COST, OVERHEAD_COST, TOTAL_COST, PRODUCTION_QTY, ACTUAL_UNIT_COST, USE_YN, REMARK, CREATED_AT, UPDATED_AT)
SELECT SEQ_ACTUAL_COST_DAILY.NEXTVAL,
       TO_DATE('2026-04-16', 'YYYY-MM-DD'),
       (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002'),
       (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-B'),
       9950, 1920, 1270, 13140, 4020, 13140,
       'Y', '라인B 개선 반영', TO_DATE('2026-04-16', 'YYYY-MM-DD'), TO_DATE('2026-04-16', 'YYYY-MM-DD')
FROM DUAL
WHERE EXISTS (SELECT 1 FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
  AND EXISTS (SELECT 1 FROM LINE WHERE LINE_CODE = 'LN-B')
  AND NOT EXISTS (
      SELECT 1 FROM ACTUAL_COST_DAILY
      WHERE COST_DATE = TO_DATE('2026-04-16', 'YYYY-MM-DD')
        AND ITEM_ID = (SELECT ITEM_ID FROM ITEM WHERE ITEM_CODE = 'FG-CAM-002')
        AND LINE_ID = (SELECT LINE_ID FROM LINE WHERE LINE_CODE = 'LN-B')
  );

COMMIT;
