-- =========================================================
-- CHECK SELECT FOR ALL TABLES (22 + ADDITIONAL 10)
-- =========================================================

SELECT * FROM EMP;
SELECT * FROM PROCESS;
SELECT * FROM ITEM;
SELECT * FROM EQUIPMENT;
SELECT * FROM DEFECT_CODE;

SELECT * FROM SUGGESTION_BOARD;
SELECT * FROM NOTICE_BOARD;
SELECT * FROM ANSWER;

SELECT * FROM INVENTORY;
SELECT * FROM MATERIAL_INOUT;

SELECT * FROM PRODUCTION_PLAN;
SELECT * FROM WORK_ORDER;
SELECT * FROM PRODUCTION_RESULT;
SELECT * FROM FINAL_INSPECTION;

SELECT * FROM MATERIAL_INSPECTION;
SELECT * FROM DEFECT_MATERIAL;
SELECT * FROM DEFECT_PRODUCT;

SELECT * FROM BOM;
SELECT * FROM BOM_DETAIL;
SELECT * FROM ROUTING;

SELECT * FROM EQUIPMENT_MAINTENANCE;
SELECT * FROM EQUIPMENT_FAILURE_ACTION;

SELECT * FROM LINE;
SELECT * FROM CUSTOMER;
SELECT * FROM SUPPLIER;
SELECT * FROM WAREHOUSE;
SELECT * FROM SALES_ORDER;
SELECT * FROM SHIPMENT;
SELECT * FROM PURCHASE_ORDER;
SELECT * FROM EQUIPMENT_DOWNTIME;
SELECT * FROM STANDARD_COST;
SELECT * FROM ACTUAL_COST_DAILY;
