DELETE FROM SHIPMENT;
DELETE FROM PURCHASE_ORDER;
DELETE FROM ACTUAL_COST_DAILY;
DELETE FROM STANDARD_COST;
DELETE FROM EQUIPMENT_DOWNTIME;
DELETE FROM SALES_ORDER;

DELETE FROM WAREHOUSE;
DELETE FROM SUPPLIER;
DELETE FROM CUSTOMER;
DELETE FROM LINE;

DELETE FROM EQUIPMENT_FAILURE_ACTION;
DELETE FROM DEFECT_PRODUCT;
DELETE FROM DEFECT_MATERIAL;

DELETE FROM FINAL_INSPECTION;
DELETE FROM MATERIAL_INSPECTION;

DELETE FROM PRODUCTION_RESULT;
DELETE FROM WORK_ORDER;
DELETE FROM PRODUCTION_PLAN;

DELETE FROM MATERIAL_INOUT;
DELETE FROM INVENTORY;

DELETE FROM BOM_DETAIL;
DELETE FROM BOM;
DELETE FROM ROUTING;

DELETE FROM ANSWER;
DELETE FROM NOTICE_BOARD;
DELETE FROM SUGGESTION_BOARD;

DELETE FROM EQUIPMENT_MAINTENANCE;

DELETE FROM DEFECT_CODE;
DELETE FROM EQUIPMENT;
DELETE FROM ITEM;
DELETE FROM PROCESS;
DELETE FROM EMP;

COMMIT;
