-- =========================================================
-- BeginAgain_additional_tables.sql
-- 신규 테이블만 추가 생성 / 기존 테이블 PK, FK, SEQUENCE는 그대로 유지
-- Oracle SQL
-- =========================================================

-- =========================================================
-- 1. TABLE CREATE
-- =========================================================

CREATE TABLE LINE (
    LINE_ID             NUMBER          NOT NULL,
    LINE_CODE           VARCHAR2(30)    NULL,
    LINE_NAME           VARCHAR2(100)   NULL,
    LINE_TYPE           VARCHAR2(30)    NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_LINE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID         NUMBER          NOT NULL,
    CUSTOMER_CODE       VARCHAR2(30)    NULL,
    CUSTOMER_NAME       VARCHAR2(100)   NULL,
    MANAGER_NAME        VARCHAR2(50)    NULL,
    PHONE               VARCHAR2(30)    NULL,
    EMAIL               VARCHAR2(100)   NULL,
    ADDRESS             VARCHAR2(300)   NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_CUSTOMER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE SUPPLIER (
    SUPPLIER_ID         NUMBER          NOT NULL,
    SUPPLIER_CODE       VARCHAR2(30)    NULL,
    SUPPLIER_NAME       VARCHAR2(100)   NULL,
    MANAGER_NAME        VARCHAR2(50)    NULL,
    PHONE               VARCHAR2(30)    NULL,
    EMAIL               VARCHAR2(100)   NULL,
    ADDRESS             VARCHAR2(300)   NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_SUPPLIER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE WAREHOUSE (
    WAREHOUSE_ID        NUMBER          NOT NULL,
    WAREHOUSE_CODE      VARCHAR2(30)    NULL,
    WAREHOUSE_NAME      VARCHAR2(100)   NULL,
    WAREHOUSE_TYPE      VARCHAR2(30)    NULL,
    LOCATION            VARCHAR2(100)   NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_WAREHOUSE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE SALES_ORDER (
    SALES_ORDER_ID      NUMBER          NOT NULL,
    ORDER_NO            VARCHAR2(30)    NULL,
    CUSTOMER_ID         NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    ORDER_DATE          DATE            NULL,
    DUE_DATE            DATE            NULL,
    ORDER_QTY           NUMBER(15,3)    NULL,
    UNIT_PRICE          NUMBER(15,2)    NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    PRIORITY            VARCHAR2(20)    NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_SALES_ORDER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE SHIPMENT (
    SHIPMENT_ID         NUMBER          NOT NULL,
    SHIPMENT_NO         VARCHAR2(30)    NULL,
    SALES_ORDER_ID      NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    LOT_NO              VARCHAR2(50)    NULL,
    SHIP_DATE           DATE            NULL,
    DUE_DATE            DATE            NULL,
    SHIP_QTY            NUMBER(15,3)    NULL,
    ON_TIME_YN          CHAR(1)         DEFAULT 'Y' NOT NULL,
    STATUS              VARCHAR2(20)    NULL,
    DELAY_REASON        VARCHAR2(300)   NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_SHIPMENT_ON_TIME_YN CHECK (ON_TIME_YN IN ('Y', 'N')),
    CONSTRAINT CK_SHIPMENT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE PURCHASE_ORDER (
    PURCHASE_ORDER_ID   NUMBER          NOT NULL,
    PURCHASE_NO         VARCHAR2(30)    NULL,
    SUPPLIER_ID         NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    ORDER_DATE          DATE            NULL,
    EXPECTED_IN_DATE    DATE            NULL,
    ORDER_QTY           NUMBER(15,3)    NULL,
    UNIT_PRICE          NUMBER(15,2)    NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    NULL,
    STATUS              VARCHAR2(20)    NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_PURCHASE_ORDER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE EQUIPMENT_DOWNTIME (
    DOWNTIME_ID         NUMBER          NOT NULL,
    EQUIPMENT_ID        NUMBER          NOT NULL,
    LINE_ID             NUMBER          NULL,
    WORK_ORDER_ID       NUMBER          NULL,
    START_TIME          DATE            NULL,
    END_TIME            DATE            NULL,
    DOWNTIME_MIN        NUMBER          NULL,
    DOWNTIME_TYPE       VARCHAR2(30)    NULL,
    CAUSE_CODE          VARCHAR2(30)    NULL,
    CAUSE_DETAIL        VARCHAR2(300)   NULL,
    STATUS              VARCHAR2(20)    NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_EQUIPMENT_DOWNTIME_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE STANDARD_COST (
    STANDARD_COST_ID    NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    EFFECTIVE_FROM      DATE            NULL,
    EFFECTIVE_TO        DATE            NULL,
    MATERIAL_COST       NUMBER(15,2)    NULL,
    LABOR_COST          NUMBER(15,2)    NULL,
    OVERHEAD_COST       NUMBER(15,2)    NULL,
    STANDARD_UNIT_COST  NUMBER(15,2)    NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_STANDARD_COST_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE ACTUAL_COST_DAILY (
    ACTUAL_COST_ID      NUMBER          NOT NULL,
    COST_DATE           DATE            NULL,
    ITEM_ID             NUMBER          NOT NULL,
    LINE_ID             NUMBER          NULL,
    MATERIAL_COST       NUMBER(15,2)    NULL,
    LABOR_COST          NUMBER(15,2)    NULL,
    OVERHEAD_COST       NUMBER(15,2)    NULL,
    TOTAL_COST          NUMBER(15,2)    NULL,
    PRODUCTION_QTY      NUMBER(15,3)    NULL,
    ACTUAL_UNIT_COST    NUMBER(15,2)    NULL,
    USE_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    REMARK              VARCHAR2(300)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT CK_ACTUAL_COST_DAILY_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- =========================================================
-- 2. PRIMARY KEY
-- =========================================================

ALTER TABLE LINE ADD CONSTRAINT PK_LINE PRIMARY KEY (LINE_ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID);
ALTER TABLE WAREHOUSE ADD CONSTRAINT PK_WAREHOUSE PRIMARY KEY (WAREHOUSE_ID);
ALTER TABLE SALES_ORDER ADD CONSTRAINT PK_SALES_ORDER PRIMARY KEY (SALES_ORDER_ID);
ALTER TABLE SHIPMENT ADD CONSTRAINT PK_SHIPMENT PRIMARY KEY (SHIPMENT_ID);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT PK_PURCHASE_ORDER PRIMARY KEY (PURCHASE_ORDER_ID);
ALTER TABLE EQUIPMENT_DOWNTIME ADD CONSTRAINT PK_EQUIPMENT_DOWNTIME PRIMARY KEY (DOWNTIME_ID);
ALTER TABLE STANDARD_COST ADD CONSTRAINT PK_STANDARD_COST PRIMARY KEY (STANDARD_COST_ID);
ALTER TABLE ACTUAL_COST_DAILY ADD CONSTRAINT PK_ACTUAL_COST_DAILY PRIMARY KEY (ACTUAL_COST_ID);

-- =========================================================
-- 3. UNIQUE
-- =========================================================

ALTER TABLE LINE ADD CONSTRAINT UQ_LINE_CODE UNIQUE (LINE_CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT UQ_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE);
ALTER TABLE SUPPLIER ADD CONSTRAINT UQ_SUPPLIER_CODE UNIQUE (SUPPLIER_CODE);
ALTER TABLE WAREHOUSE ADD CONSTRAINT UQ_WAREHOUSE_CODE UNIQUE (WAREHOUSE_CODE);
ALTER TABLE SALES_ORDER ADD CONSTRAINT UQ_SALES_ORDER_ORDER_NO UNIQUE (ORDER_NO);
ALTER TABLE SHIPMENT ADD CONSTRAINT UQ_SHIPMENT_NO UNIQUE (SHIPMENT_NO);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT UQ_PURCHASE_ORDER_NO UNIQUE (PURCHASE_NO);

-- =========================================================
-- 4. FOREIGN KEY
-- 기존 테이블은 그대로 두고, 신규 테이블끼리/기존 테이블 참조만 추가
-- =========================================================

ALTER TABLE SALES_ORDER
    ADD CONSTRAINT FK_SALES_ORDER_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE SALES_ORDER
    ADD CONSTRAINT FK_SALES_ORDER_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);

ALTER TABLE SHIPMENT
    ADD CONSTRAINT FK_SHIPMENT_SALES_ORDER
    FOREIGN KEY (SALES_ORDER_ID) REFERENCES SALES_ORDER (SALES_ORDER_ID);

ALTER TABLE SHIPMENT
    ADD CONSTRAINT FK_SHIPMENT_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);

ALTER TABLE PURCHASE_ORDER
    ADD CONSTRAINT FK_PURCHASE_ORDER_SUPPLIER
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID);

ALTER TABLE PURCHASE_ORDER
    ADD CONSTRAINT FK_PURCHASE_ORDER_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);

ALTER TABLE EQUIPMENT_DOWNTIME
    ADD CONSTRAINT FK_EQUIPMENT_DOWNTIME_EQUIP
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT (EQUIPMENT_ID);

ALTER TABLE EQUIPMENT_DOWNTIME
    ADD CONSTRAINT FK_EQUIPMENT_DOWNTIME_LINE
    FOREIGN KEY (LINE_ID) REFERENCES LINE (LINE_ID);

ALTER TABLE EQUIPMENT_DOWNTIME
    ADD CONSTRAINT FK_EQUIPMENT_DOWNTIME_WO_ORDER
    FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER (WORK_ORDER_ID);

ALTER TABLE STANDARD_COST
    ADD CONSTRAINT FK_STANDARD_COST_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);

ALTER TABLE ACTUAL_COST_DAILY
    ADD CONSTRAINT FK_ACTUAL_COST_DAILY_ITEM
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID);

ALTER TABLE ACTUAL_COST_DAILY
    ADD CONSTRAINT FK_ACTUAL_COST_DAILY_LINE
    FOREIGN KEY (LINE_ID) REFERENCES LINE (LINE_ID);

-- =========================================================
-- 5. SEQUENCE
-- =========================================================

CREATE SEQUENCE SEQ_LINE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CUSTOMER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUPPLIER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WAREHOUSE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SALES_ORDER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SHIPMENT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASE_ORDER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EQUIPMENT_DOWNTIME START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STANDARD_COST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACTUAL_COST_DAILY START WITH 1 INCREMENT BY 1;

COMMIT;

SELECT * FROM LINE;
