-- =========================================================
-- 1. FOREIGN KEY 먼저 제거
-- =========================================================

ALTER TABLE ANSWER DROP CONSTRAINT FK_ANSWER_SUGGESTION;
ALTER TABLE ANSWER DROP CONSTRAINT FK_ANSWER_WRITER_EMP;

ALTER TABLE NOTICE_BOARD DROP CONSTRAINT FK_NOTICE_BOARD_WRITER_EMP;

ALTER TABLE EQUIPMENT_FAILURE_ACTION DROP CONSTRAINT FK_EFA_MAINTENANCE;

ALTER TABLE SUGGESTION_BOARD DROP CONSTRAINT FK_SUGGESTION_BOARD_WRITER_EMP;

ALTER TABLE ROUTING DROP CONSTRAINT FK_ROUTING_ITEM;
ALTER TABLE ROUTING DROP CONSTRAINT FK_ROUTING_PROCESS;
ALTER TABLE ROUTING DROP CONSTRAINT FK_ROUTING_EQUIPMENT;

ALTER TABLE INVENTORY DROP CONSTRAINT FK_INVENTORY_ITEM;

ALTER TABLE MATERIAL_INOUT DROP CONSTRAINT FK_MATERIAL_INOUT_ITEM;

ALTER TABLE WORK_ORDER DROP CONSTRAINT FK_WORK_ORDER_ITEM;
ALTER TABLE WORK_ORDER DROP CONSTRAINT FK_WORK_ORDER_PLAN;
ALTER TABLE WORK_ORDER DROP CONSTRAINT FK_WORK_ORDER_EMP;

ALTER TABLE EQUIPMENT_MAINTENANCE DROP CONSTRAINT FK_EQ_MT_EQP;

ALTER TABLE FINAL_INSPECTION DROP CONSTRAINT FK_FINAL_INSPECTION_RESULT;
ALTER TABLE FINAL_INSPECTION DROP CONSTRAINT FK_FINAL_INSPECTION_EMP;

ALTER TABLE BOM DROP CONSTRAINT FK_BOM_ITEM;

ALTER TABLE BOM_DETAIL DROP CONSTRAINT FK_BOM_DETAIL_BOM;
ALTER TABLE BOM_DETAIL DROP CONSTRAINT FK_BOM_DETAIL_ITEM;

ALTER TABLE PRODUCTION_PLAN DROP CONSTRAINT FK_PRODUCTION_PLAN_ITEM;

ALTER TABLE DEFECT_PRODUCT DROP CONSTRAINT FK_DF_PRD_FIN;
ALTER TABLE DEFECT_PRODUCT DROP CONSTRAINT FK_DEFECT_PRODUCT_CODE;

ALTER TABLE PRODUCTION_RESULT DROP CONSTRAINT FK_PR_RES_WO;

ALTER TABLE DEFECT_MATERIAL DROP CONSTRAINT FK_DEFECT_MATERIAL_INSPECTION;
ALTER TABLE DEFECT_MATERIAL DROP CONSTRAINT FK_DEFECT_MATERIAL_CODE;

ALTER TABLE MATERIAL_INSPECTION DROP CONSTRAINT FK_MATERIAL_INSPECTION_ITEM;
ALTER TABLE MATERIAL_INSPECTION DROP CONSTRAINT FK_MATERIAL_INSPECTION_EMP;

ALTER TABLE SALES_ORDER DROP CONSTRAINT FK_SALES_ORDER_CUSTOMER;
ALTER TABLE SALES_ORDER DROP CONSTRAINT FK_SALES_ORDER_ITEM;

ALTER TABLE SHIPMENT DROP CONSTRAINT FK_SHIPMENT_SALES_ORDER;
ALTER TABLE SHIPMENT DROP CONSTRAINT FK_SHIPMENT_ITEM;

ALTER TABLE PURCHASE_ORDER DROP CONSTRAINT FK_PURCHASE_ORDER_SUPPLIER;
ALTER TABLE PURCHASE_ORDER DROP CONSTRAINT FK_PURCHASE_ORDER_ITEM;

ALTER TABLE EQUIPMENT_DOWNTIME DROP CONSTRAINT FK_EQUIPMENT_DOWNTIME_WO_ORDER;
ALTER TABLE EQUIPMENT_DOWNTIME DROP CONSTRAINT FK_EQUIPMENT_DOWNTIME_EQUIP;
ALTER TABLE EQUIPMENT_DOWNTIME DROP CONSTRAINT FK_EQUIPMENT_DOWNTIME_LINE;

ALTER TABLE STANDARD_COST DROP CONSTRAINT FK_STANDARD_COST_ITEM;

ALTER TABLE ACTUAL_COST_DAILY DROP CONSTRAINT FK_ACTUAL_COST_DAILY_ITEM;
ALTER TABLE ACTUAL_COST_DAILY DROP CONSTRAINT FK_ACTUAL_COST_DAILY_LINE;

-- =========================================================
-- 2. TABLE DROP (의존성 역순)
-- =========================================================

DROP TABLE SHIPMENT CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ORDER CASCADE CONSTRAINTS;
DROP TABLE ACTUAL_COST_DAILY CASCADE CONSTRAINTS;
DROP TABLE STANDARD_COST CASCADE CONSTRAINTS;
DROP TABLE EQUIPMENT_DOWNTIME CASCADE CONSTRAINTS;
DROP TABLE SALES_ORDER CASCADE CONSTRAINTS;

DROP TABLE WAREHOUSE CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE LINE CASCADE CONSTRAINTS;

DROP TABLE ANSWER CASCADE CONSTRAINTS;
DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
DROP TABLE EQUIPMENT_FAILURE_ACTION CASCADE CONSTRAINTS;
DROP TABLE SUGGESTION_BOARD CASCADE CONSTRAINTS;

DROP TABLE ROUTING CASCADE CONSTRAINTS;
DROP TABLE INVENTORY CASCADE CONSTRAINTS;
DROP TABLE MATERIAL_INOUT CASCADE CONSTRAINTS;
DROP TABLE WORK_ORDER CASCADE CONSTRAINTS;

DROP TABLE EQUIPMENT_MAINTENANCE CASCADE CONSTRAINTS;
DROP TABLE FINAL_INSPECTION CASCADE CONSTRAINTS;

DROP TABLE BOM_DETAIL CASCADE CONSTRAINTS;
DROP TABLE BOM CASCADE CONSTRAINTS;

DROP TABLE PRODUCTION_PLAN CASCADE CONSTRAINTS;
DROP TABLE DEFECT_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PRODUCTION_RESULT CASCADE CONSTRAINTS;
DROP TABLE DEFECT_MATERIAL CASCADE CONSTRAINTS;
DROP TABLE MATERIAL_INSPECTION CASCADE CONSTRAINTS;

DROP TABLE PROCESS CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE DEFECT_CODE CASCADE CONSTRAINTS;
DROP TABLE EMP CASCADE CONSTRAINTS;
DROP TABLE EQUIPMENT CASCADE CONSTRAINTS;

-- =========================================================
-- 3. SEQUENCE DROP
-- =========================================================

DROP SEQUENCE SEQ_LINE;
DROP SEQUENCE SEQ_CUSTOMER;
DROP SEQUENCE SEQ_SUPPLIER;
DROP SEQUENCE SEQ_WAREHOUSE;
DROP SEQUENCE SEQ_SALES_ORDER;
DROP SEQUENCE SEQ_SHIPMENT;
DROP SEQUENCE SEQ_PURCHASE_ORDER;
DROP SEQUENCE SEQ_EQUIPMENT_DOWNTIME;
DROP SEQUENCE SEQ_STANDARD_COST;
DROP SEQUENCE SEQ_ACTUAL_COST_DAILY;

DROP SEQUENCE SEQ_PROCESS;
DROP SEQUENCE SEQ_ANSWER;
DROP SEQUENCE SEQ_NOTICE_BOARD;
DROP SEQUENCE SEQ_EQUIPMENT_FAILURE_ACTION;
DROP SEQUENCE SEQ_ITEM;
DROP SEQUENCE SEQ_SUGGESTION_BOARD;
DROP SEQUENCE SEQ_ROUTING;
DROP SEQUENCE SEQ_INVENTORY;
DROP SEQUENCE SEQ_MATERIAL_INOUT;
DROP SEQUENCE SEQ_WORK_ORDER;
DROP SEQUENCE SEQ_DEFECT_CODE;
DROP SEQUENCE SEQ_EQUIPMENT_MAINTENANCE;
DROP SEQUENCE SEQ_FINAL_INSPECTION;
DROP SEQUENCE SEQ_EMP;
DROP SEQUENCE SEQ_BOM;
DROP SEQUENCE SEQ_BOM_DETAIL;
DROP SEQUENCE SEQ_PRODUCTION_PLAN;
DROP SEQUENCE SEQ_DEFECT_PRODUCT;
DROP SEQUENCE SEQ_PRODUCTION_RESULT;
DROP SEQUENCE SEQ_EQUIPMENT;
DROP SEQUENCE SEQ_DEFECT_MATERIAL;
DROP SEQUENCE SEQ_MATERIAL_INSPECTION;

COMMIT;
