<%@ page contentType="text/html; charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<div class="taPageActions"><button type="button" class="taBtn taBtnPrimary"  data-modal-target="registerModal">등록</button><button type="submit" form="deleteForm" class="taBtn taBtnOutline" onclick="return confirm('선택한 사원을 삭제하시겠습니까?');">선택 삭제</button></div>
<form class="taLocalSearchForm" data-table-id="memberTable"><div class="taToolbarRow"><div class="taToolbarField"><select class="taSelect" name="searchType"><option value="all">전체</option><option value="empNo">사번</option><option value="empName">이름</option><option value="deptCode">부서</option><option value="positionName">직급</option></select></div><div class="taToolbarField taToolbarFieldGrow" style="grid-column: span 3;"><div class="taSearchBox"><input type="text" class="taSearchInput" name="keyword" placeholder="검색어를 입력하세요"><button type="submit" class="taSearchBtn">⌕</button><button type="button" class="taBtn taBtnOutline taSearchReset">초기화</button></div></div></div></form>
<form id="deleteForm" action="${pageContext.request.contextPath}/member/delete" method="post"><div class="taTableShell"><div class="taTableScroll"><table class="taMesTable" id="memberTable">
<thead><tr><th class="taTableHeadCell taCheckCell"><input type="checkbox" id="checkAll" class="taCheckInput"></th><th class="taTableHeadCell taColFit">ID</th><th class="taTableHeadCell taColFit">사번</th><th class="taTableHeadCell taColFit">이름</th><th class="taTableHeadCell taColFit">부서</th><th class="taTableHeadCell taColFit">직급</th><th class="taTableHeadCell taColFit">상태</th><th class="taTableHeadCell taColFit">권한</th><th class="taTableHeadCell taColFit">임시비밀번호</th><th class="taTableHeadCell taColAction taLastCol">상세</th></tr></thead>
<tbody><c:choose><c:when test="${not empty memberList}"><c:forEach var="m" items="${memberList}"><tr class="taTableBodyRow"><td class="taTableBodyCell taCheckCell"><input type="checkbox" name="empId" value="${m.empId}" class="taCheckInput"></td><td class="taTableBodyCell taColFit">${m.empId}</td><td class="taTableBodyCell taColFit" data-search-key="empNo">${m.empNo}</td><td class="taTableBodyCell taColFit" data-search-key="empName">${m.empName}</td><td class="taTableBodyCell taColFit" data-search-key="deptCode">${m.deptCode}</td><td class="taTableBodyCell taColFit" data-search-key="positionName">${m.positionName}</td><td class="taTableBodyCell taColFit">${m.status}</td><td class="taTableBodyCell taColFit">${m.roleName}</td><td class="taTableBodyCell taColFit">${m.tempPwdYn}</td><td class="taTableBodyCell taColAction taLastCol"><a class="taLinkAnchor" href="${pageContext.request.contextPath}/member/detail?empId=${m.empId}">상세보기</a></td></tr></c:forEach></c:when><c:otherwise><tr class="taTableBodyRow"><td class="taTableBodyCell taLastCol" colspan="10" style="text-align:center;">조회된 사원이 없습니다.</td></tr></c:otherwise></c:choose></tbody>
</table></div></div></form>
<div class="taModal" id="registerModal" hidden aria-hidden="true"><div class="taModalDialog modal-lg"><div class="taModalHeader"><h3 class="taModalTitle">사원 등록</h3><button type="button" class="taModalClose">&times;</button></div><form action="${pageContext.request.contextPath}/member/register" method="post"><div class="taModalBody taModalGrid"><div class="form-row"><label>사번</label><input type="text" name="empNo" required></div><div class="form-row"><label>이름</label><input type="text" name="empName" required></div><div class="form-row"><label>부서코드</label><input type="text" name="deptCode"></div><div class="form-row"><label>직급</label><input type="text" name="positionName"></div><div class="form-row"><label>이메일</label><input type="text" name="email"></div><div class="form-row"><label>전화번호</label><input type="text" name="phone"></div><div class="form-row"><label>상태</label><input type="text" name="status" value="ACTIVE"></div><div class="form-row"><label>권한</label><input type="text" name="roleName" value="USER"></div><div class="form-row full"><label>비고</label><textarea name="remark"></textarea></div></div><div class="taModalFooter"><button type="button" class="taBtn taBtnOutline taModalClose">취소</button><button type="submit" class="taBtn taBtnPrimary">등록</button></div></form></div></div>
